- anomalib/core/model/inference.py
- anomalib/data/mvtec.py
- anomalib/data/transforms/pre_process.py
This PR fixes the compatibility issues with OTE SDK. After tagging this version as v0.1.2+, GitHub should be fully compatible
> Address compatibility issues with OTE, that are caused by the legacy code.

- .gitignore
- anomalib/core/callbacks/visualizer_callback.py
- anomalib/loggers/__init__.py
- anomalib/loggers/tensorboard.py
- anomalib/loggers/wandb.py
- requirements/requirements.txt
- tests/loggers/test_get_logger.py
- Add `wandb` logger.
- The docstring in `AnomalibWandbLogger` module is copied from the pytorch lightning wandb logger module. This is because the anomalib one just adds two more functions.
- Another method was added to `visualizer_callback` so that we can log images to wandb in batch rather than sequentially at each `log` call. This is because if images are not provided in batches, they get logged at a different step. So we can't see all the images side by side on the dashboard. Batch operation ensures they are available side by side.
> Add `wandb` logger

- .github/workflows/docs.yml
- README.md
- Fix checkout for existing branch
> Address docs build failing issue

- anomalib/utils/post_process.py
Quick fix for the inverted anomaly heatmaps in OTE. Maybe we should include this in 0.2.3 to prevent an additional round of testing.
> fix heatmap color scheme

- anomalib/data/__init__.py
- anomalib/data/mvtec.py
This PR solves the problems with incorrect train/val/test splits. The seed from the config is now used when the splits are created. Also the `create_validation_set` argument of the `make_mvtec_dataset` now takes effect when set to True.
> Bugfix: fix random val/test split issue

- anomalib/core/model/inference.py
Quick PR to accommodate the latest changes to the OTE normalization branch.
> add distinction between image and pixel threshold in postprocessor

- anomalib/data/mvtec.py
- requirements/base.txt
- tests/helpers/detection.py
- tests/models/test_model.py
- tests/utils/test_download_progress_bar.py
> Fix networkx requirement

- .github/workflows/tox.yml
- tests/helpers/dataset.py
- tox.ini
- Use environment variable for dataset path. This will make the tests agnostic to the machine on which it is run on.
- The workflow file is changed to point to the dataset path on the server.
> Change hardcoded dataset path to environ variable

- anomalib/core/callbacks/min_max_normalization.py
- anomalib/core/model/anomaly_module.py
- tests/core/callbacks/normalization_callback/test_normalization_callback.py
- Moves the metrics and the collected outputs to the cpu to reduce GPU memory use
> perform metric computation on cpu

- anomalib/config/config.py
Weight files specified as arg is not loaded and defaulted to file specified in the config file. Minor bug in config.py.
> Fixed issue with model loading

- anomalib/data/tiler.py
- This PR replaces `SupportIndex` with `int`, which was an artifact from commits from long time ago.
- Fixes #72
> Replace `SupportIndex` with `int`

- anomalib/deploy/inferencers/torch.py
- anomalib/models/cflow/README.md
- As suggested by the community, this PR fixes the mixed data type issue reported in #67
```
patchcore inference:
File "d:\projects\anomalib\anomalib\utils\normalization\min_max.py", line 31, in normalize
normalized = ((targets - threshold) / (max_val - min_val)) + 0.5
TypeError: unsupported operand type(s) for -: 'numpy.ndarray' and 'Tensor'
```
- Fixes #67
> Fix Mix Data type issue on inferencer

- anomalib/core/metrics/auroc.py
- tox.ini
This PR adds reordering to the AUC computation, but applies it only when necessary (i.e. `tpr` is not increasing or decreasing). This prevents the situation where the `tpr` elements corresponding to duplicate values in the `fpr` array get reordered in an unpredictable manner due to unstable sorting, which in turn may lead to underestimation of the performance score (see my comment under [this PR](https://github.com/openvinotoolkit/anomalib/pull/90)).
> Reorder auc only when needed

- anomalib/utils/sweep/helpers/inference.py
- tools/benchmarking/benchmark.py
This is a quick fix to the following issues
- Even with model.eval(), the models returned predictions with `grad_required = True`
- Due to incorrect calculation of splits, greater number of GPUs were being assigned
> 🐞 Fix tensor detach and gpu count issues in benchmarking script

- anomalib/models/components/base/anomaly_module.py
- Returns predicted masks in the predict step, needed for OTE Segmentation.
> Return predicted masks in predict step

- anomalib/models/components/dimensionality_reduction/random_projection.py
Fixing https://github.com/openvinotoolkit/anomalib/issues/111
> c_idx cast to LongTensor in random sparse projection

- anomalib/models/patchcore/model.py
Hey,
I realized that the `compute_anomy_score` method https://github.com/openvinotoolkit/anomalib/blob/ee8807b48d7c5ccfe9f5ff976fb6d6dac0247f0a/anomalib/models/patchcore/model.py#L69 can be optimized by using torch native functions that might vectorize better.
Using a GPU, the execution time reduces from `0.17330350000000116s` to `0.00022549999999910142s` (~700x faster)
> optimize compute_anomaly_score by using torch native funcrtions

- anomalib/utils/metrics/adaptive_threshold.py
- tests/pre_merge/utils/metrics/__init__.py
- tests/pre_merge/utils/metrics/test_adaptive_threshold.py
- This PR addresses a bug causing validation to fail when computing the adaptive threshold. In rare cases (e.g. few anomalous images in validation set), it is possible that the recall is 1.0 for all threshold values included in TorchMetrics precision-recall curve computation. In this case, the `thresholds` tensor gets reduced to a scalar value, and trying to retrieve the first item produces an `IndexError`. In this case we can safely return the scalar threshold value instead.
> Fix IndexError in adaptive threshold computation

- anomalib/models/components/base/anomaly_module.py
- tests/pre_merge/utils/metrics/test_adaptive_threshold.py
- Uses the default threshold values specified by the user when creating the F1 metrics. This makes sure that when adaptive thresholding is disabled, and no normalization is used, the F1 computation will be based on the user-specified threshold.
- Adds a test case that checks if the thresholds get assigned correctly in the above conditions.
- Fixes https://github.com/openvinotoolkit/anomalib/issues/139
> fix non-adaptive thresholding bug

- anomalib/models/patchcore/model.py
Fixing https://github.com/openvinotoolkit/anomalib/issues/40
> Calculate feature map shape patchcore

- anomalib/data/btech.py
- anomalib/models/dfkde/model.py
- anomalib/models/dfm/model.py
- anomalib/models/padim/model.py
- anomalib/utils/callbacks/visualizer_callback.py
- tox.ini
- This PR converts `bmp` images to `png` after downloading and extracting the `BTech` dataset. 
Each BTech category has different image extension as follows
| Category | Image | Mask |
|----------|-------|------|
| 01       | bmp   | png  |
| 02       | png   | png  |
| 03       | bmp   | bmp  |
To avoid any conflict, the following script converts all the extensions to png. This solution works fine, but it's also possible to properly ready the bmp and png filenames from categories in `make_btech_dataset` function.
> Added extension as an option when saving the result images.

- .pre-commit-config.yaml
- anomalib/data/folder.py
- anomalib/models/cflow/model.py
- anomalib/models/components/dimensionality_reduction/random_projection.py
- anomalib/models/components/stats/kde.py
- anomalib/models/ganomaly/torch_model.py
- anomalib/utils/callbacks/visualizer_callback.py
- requirements/dev.txt
- tox.ini
- This hotfix proposes a fix to return `label` in `folder` dataset when `classification` task is chosen. Currently the `folder` dataset doesn't return `label` in `classification`, which ultimately causes a failed validation.
- PR also bumps up the black version due to a version dependency, resulting in some changes in some modules.
- Fixes #173
> Fix `KeyError:'label'` in classification folder dataset

- README.md
- anomalib/data/btech.py
- anomalib/data/folder.py
- anomalib/data/mvtec.py
- anomalib/data/utils/split.py
- anomalib/models/cflow/README.md
- anomalib/models/dfkde/README.md
- anomalib/models/dfm/README.md
- anomalib/models/ganomaly/README.md
- anomalib/models/padim/README.md
- anomalib/models/patchcore/README.md
- anomalib/models/stfpm/README.md
- docs/source/guides/getting_started.rst
- docs/source/research/benchmark.md
- tests/helpers/dataset.py
- tests/nightly/models/test_model_nightly.py
- tests/pre_merge/datasets/test_dataset.py
- tools/benchmarking/README.md
- This PR adds CC BY-NC-SA 4.0 license to MVTec in the repo, as required by the license type.
> Added MVTec license to the repo

- anomalib/models/cflow/backbone.py
- anomalib/models/cflow/config.yaml
- anomalib/models/cflow/model.py
- This PR switches soft permutation to false by default to speed up training.
- Add this as a configurable parameter so the user could choose.
- Fixes #89
> 🔄 CFlow: Switch soft permutation to false by default to speed up training.

- anomalib/models/dfkde/model.py
- anomalib/models/dfkde/normality_model.py
- anomalib/models/dfkde/torch_model.py
- Refactor dfkde model.
- Fixes #129
> Refactor DFKDE model

- anomalib/utils/callbacks/cdf_normalization.py
- anomalib/utils/callbacks/min_max_normalization.py
- anomalib/utils/callbacks/model_loader.py
- anomalib/utils/callbacks/openvino.py
- anomalib/utils/callbacks/visualizer_callback.py
- tests/nightly/models/test_model_nightly.py
- Updates pl.LightningModule to AnomalyModule
- Fixes #65 
- Final change depends on PR #178 to get merged
> Minor fixes: Update callbacks to AnomalyModule

- tools/inference.py
- Add stream function to go over all images in a directory if it is provided as the image path.
- Fixes #182
> ✨ Directory streaming

- docs/source/guides/developing_on_docker.rst
Updates the [Developing on Docker](https://github.com/openvinotoolkit/anomalib/blob/development/docs/source/guides/developing_on_docker.rst) guide following the enhancements of the Dockerfile as per #172.
Since VSCode is not a necessity for building and running the Docker container, I removed all details regarding the use of VSCode from the docs.
> Updated documentation for development on Docker

- anomalib/data/utils/image.py
- anomalib/models/ganomaly/model.py
- anomalib/models/ganomaly/torch_model.py
- Computes padding based on the image size. Might not be the best approach.
- Fixes #136
> 🐞fix support for non-square images

- anomalib/models/dfm/config.yaml
- anomalib/models/dfm/dfm_model.py
- anomalib/models/dfm/model.py
- Two additional parameters need to be specified for DFM: name of the layer from which features are extracted, and an integer pool factor. The features will be average-pooled by the specified pool factor before DFM is applied.
> Allow specifying feature layer and pool factor in DFM

- anomalib/utils/callbacks/timer.py
- tools/benchmarking/benchmark.py
- Supress outputs from model and print values from benchmarking script
- Fixes #185
> Fix inconsistent benchmarking throughput/time

- anomalib/data/__init__.py
- anomalib/data/folder.py
- tests/pre_merge/datasets/test_dataset.py
This PR addresses https://github.com/openvinotoolkit/anomalib/issues/180#issuecomment-1084564180
If you provide a `config.dataset.normal_test` to the datamodule, you can now define test data in a folder datamodule.
> assign test split for folder dataset

- setup.py
- 🛠 Fix `get_version` in `setup.py` to avoid hard-coding version.
- Fixes #36
> 🛠 Fix `get_version` in `setup.py` to avoid hard-coding version.

- anomalib/utils/callbacks/visualizer_callback.py
- anomalib/utils/loggers/wandb.py
- Fixes logging images to Tensorboard and wandb.
- Now works with multiple loggers.
- x ] My code follows the [pre-commit style and check guidelines](https://openvinotoolkit.github.io/anomalib/guides/using_pre_commit.html#pre-commit-hooks) of this project.
> 🐞 Fix image loggers

- anomalib/models/cflow/config.yaml
- anomalib/models/components/base/anomaly_module.py
- anomalib/models/dfkde/config.yaml
- anomalib/models/dfm/config.yaml
- anomalib/models/ganomaly/config.yaml
- anomalib/models/padim/config.yaml
- anomalib/models/patchcore/config.yaml
- anomalib/models/stfpm/config.yaml
- anomalib/utils/callbacks/cdf_normalization.py
- anomalib/utils/callbacks/min_max_normalization.py
- anomalib/utils/callbacks/visualizer_callback.py
- anomalib/utils/metrics/__init__.py
- anomalib/utils/metrics/collection.py
- requirements/base.txt
- tests/pre_merge/utils/callbacks/normalization_callback/test_normalization_callback.py
- tests/pre_merge/utils/callbacks/visualizer_callback/test_visualizer.py
- tests/pre_merge/utils/metrics/test_adaptive_threshold.py
- This PR makes metrics configurable from the config.yaml. The config file is currently only updated for PADIM. Will update the other ones after feedback on this approach.
- Fixes https://github.com/openvinotoolkit/anomalib/issues/226, https://github.com/openvinotoolkit/anomalib/issues/199
> Configurable metrics

- tools/benchmarking/benchmark.py
- tools/benchmarking/benchmark_params.yaml
- OpenVINO throughput is optional now. This should mitigate any errors caused by incorrect/missing installation.
> Make OpenVINO throughput optional in benchmarking

- anomalib/config/config.py
- anomalib/models/__init__.py
- anomalib/models/cflow/config.yaml
- anomalib/models/dfkde/config.yaml
- anomalib/models/dfm/config.yaml
- anomalib/models/ganomaly/config.yaml
- anomalib/models/padim/config.yaml
- anomalib/models/patchcore/config.yaml
- anomalib/models/stfpm/config.yaml
- tests/helpers/config.py
- tests/pre_merge/utils/callbacks/openvino_callback/dummy_config.yml
- Fix configs to properly use `pytorch-lightning==1.6.*` and train with GPU
- Fixes #232
> Fix configs to properly use pytorch-lightning==1.6 with GPU

- README.md
- anomalib/config/config.py
- anomalib/deploy/inferencers/openvino.py
- docs/source/guides/getting_started.rst
- tests/helpers/config.py
- tests/pre_merge/utils/callbacks/normalization_callback/test_normalization_callback.py
- tests/pre_merge/utils/callbacks/openvino_callback/test_openvino.py
- tests/pre_merge/utils/metrics/test_adaptive_threshold.py
- tools/benchmarking/README.md
- tools/hpo/wandb_sweep.py
- tools/inference.py
- tools/test.py
- tools/train.py
- This is to address some of the DX feedback we have recently received.
- Configs contain configurable parameters not only for model but also for dataset, logging, project etc. Therefore, it should be renamed to be more generic.
> 🏷  Rename `--model_config_path` to `config`

- anomalib/data/folder.py
This change prevents folders from being scanned and added to the data samples.
> Prevent folders from being added to the samples

- anomalib/deploy/inferencers/base.py
- tools/inference.py
- Fixes #218 
I haven't tested this with OpenVINO as the installation is broken on my windows machine.
> Add segmentation mask to inference output

- anomalib/data/folder.py
- This PR fixes mask filenames that are incorrectly assigned in certain edge cases.
- Fixes #243
> 🛠  Fix mask filenames in folder dataset

- anomalib/data/folder.py
- Currently folder dataset directly assigns values to dataframe without using `.loc`, which causes the following warning:
```
SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame
See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
```
- This PR fixes this by properly assigning values to dataframe rows.
> 🔧  Properly assign values to dataframe in folder dataset.

- anomalib/data/folder.py
- anomalib/utils/callbacks/visualizer_callback.py
- This PR adds checks to see if the task is properly assigned in folder dataset.
- Fixes #273
> ➕Add warnings ⚠️ for inproper task setting in config files.

- setup.py
- Currently there is no description available in [anomalib PyPI](https://pypi.org/project/anomalib/). This PR adds the long description so it appears on PyPI.
> ➕ Add long description to `setup.py` to make `README.md` PyPI friendly.

- anomalib/data/btech.py
- anomalib/data/mvtec.py
- anomalib/data/utils/__init__.py
- anomalib/data/utils/download.py
- Check hash for files downloaded from remote location.
- Fixes #253
> ✨ Add hash check to data download

- anomalib/models/cflow/config.yaml
- anomalib/models/dfkde/config.yaml
- anomalib/models/dfm/config.yaml
- anomalib/models/ganomaly/config.yaml
- anomalib/models/padim/config.yaml
- anomalib/models/patchcore/config.yaml
- anomalib/models/stfpm/config.yaml
- anomalib/utils/callbacks/__init__.py
- anomalib/utils/callbacks/nncf/callback.py
- tests/helpers/model.py
- tests/nightly/models/test_model_nightly.py
- I have kept nncf disabled in the tests as it might not work in the CI.
> 🔨 Fix nncf key issue in nightly job

- anomalib/models/padim/config.yaml
- anomalib/post_processing/__init__.py
- anomalib/post_processing/post_process.py
- anomalib/post_processing/visualizer.py
- anomalib/utils/callbacks/visualizer_callback.py
- tests/pre_merge/post_processing/test_visualizer.py
- tools/inference.py
First part of the visualizer refactor. Improves the looks of the images, especially for classification.
Example image for classification:
Example image for segmentation:
Also improves the logic within the visualizer callback class.
- #289
> Visualizer improvements pt1

- anomalib/models/cflow/config.yaml
- anomalib/models/dfkde/config.yaml
- anomalib/models/dfm/config.yaml
- anomalib/models/ganomaly/config.yaml
- anomalib/models/padim/config.yaml
- anomalib/models/patchcore/config.yaml
- anomalib/models/stfpm/config.yaml
- requirements/openvino.txt
- tests/helpers/model.py
- tests/nightly/models/performance_thresholds.yaml
- tests/pre_merge/deploy/test_inferencer.py
- tox.ini
- Move inferencer tests to pre-merge as they are very fast and we need to validate them before changes to inferencers are merged.
- Set `devices` flag to 1 as all models fail with default setting. This is because if this flag is not set, all GPUs are selected and the distribute method of Pytorch Lightning is not able to pickle `FeatureExtractor`.
- Upgrade openvino as the old version throws error for inference on `xml` model.
> 🧪 Fix nightly

- anomalib/config/config.py
- Adds input_info to the NNCF config when this has not been defined by the user in the `config.yaml`.
This allows users to enable NNCF by adding the following to `config.yaml`:
```
optimization:
nncf:
apply: true
```
Where previously, the following was needed:
```
optimization:
nncf:
apply: true
input_info:
sample_size: null
```
> add input_info to nncf config when not defined by user

- tests/nightly/models/test_model_nightly.py
- tests/nightly/tools/benchmarking/test_benchmarking.py
- Increase tolerance for nightly tests
- Fix path for benchmarking tests
> 🐞 Increase tolerance + nightly path fix

- anomalib/config/config.py
- anomalib/models/cflow/config.yaml
- anomalib/models/cflow/lightning_model.py
- anomalib/models/components/base/anomaly_module.py
- anomalib/models/dfkde/config.yaml
- anomalib/models/dfkde/lightning_model.py
- anomalib/models/dfm/config.yaml
- anomalib/models/dfm/lightning_model.py
- anomalib/models/ganomaly/config.yaml
- anomalib/models/ganomaly/lightning_model.py
- anomalib/models/padim/config.yaml
- anomalib/models/padim/lightning_model.py
- anomalib/models/patchcore/config.yaml
- anomalib/models/patchcore/lightning_model.py
- anomalib/models/stfpm/config.yaml
- anomalib/models/stfpm/lightning_model.py
- anomalib/utils/callbacks/__init__.py
- anomalib/utils/callbacks/metrics_configuration.py
- anomalib/utils/metrics/adaptive_threshold.py
- tests/pre_merge/utils/callbacks/normalization_callback/test_normalization_callback.py
- tests/pre_merge/utils/callbacks/visualizer_callback/dummy_lightning_model.py
- tests/pre_merge/utils/metrics/test_adaptive_threshold.py
This PR moves the thresholding parameters outside of the model parameters section. This also removes the thresholding-related arguments from the base class, which leads to a cleaner implementation of that class. The responsibility of configuring the threshold metric classes is moved from the base task to the metrics callback.
> move threshold params to metric configuration callback

- anomalib/post_processing/visualizer.py
This PR fixes a bug that caused too many matplotlib figures to be retained in memory. `visualizer.generate()` was unintentionally called twice for every image, causing the number of open images to build up as the test loop progressed. Fixed by leaving the responsibility of calling `visualizer.generate()` to the callback class instead of the visualizer itself.
Note: Since this bug affected development, I target development in this PR. Will rebase the feature branch to pull in the changes there.
> fix too many open images warning

- anomalib/utils/metrics/__init__.py
- anomalib/utils/metrics/adaptive_threshold.py
- anomalib/utils/metrics/optimal_f1.py
- requirements/base.txt
Remove obsolete parameter from torchmetrics classes and upgrade torchmetrics version in requirement.
> Upgrade TorchMetrics version

- tox.ini
- There is an issue in `pylint==2.14.0` which incorrectly parses `tox.ini`. The idea is to use a lower version of pylint till versions >=2.14.1 are available in the pip channel.
> 🚀 Set pylint version in tox.ini

- anomalib/utils/sweep/helpers/callbacks.py
- tools/benchmarking/benchmark.py
Currently benchmarking script fails which also breaks the test in nightly
- Add MetricsConfigurationCallback to benchmarking callbacks.
Note: This adds duplicate lines from get_callbacks used in train and test to benchmark utils.
> Add metrics configuration callback to benchmarking

- anomalib/data/__init__.py
- anomalib/data/btech.py
- anomalib/data/folder.py
- anomalib/data/mvtec.py
- anomalib/models/draem/config.yaml
- anomalib/models/fastflow/config.yaml
- tests/pre_merge/datasets/test_dataset.py
- This PR refactors the name of the datamodules. This will be one of the basis of the Anomalib CLI. For example `MVTecDataModule` has been renamed to `MVTec`. This because Anomalib CLI will be able to choose the data from the CLI such as `python train.py --data MVTec`.
> 🏷️ Refactor Datamodule names 

- anomalib/data/__init__.py
- anomalib/models/__init__.py
- anomalib/utils/callbacks/__init__.py
- anomalib/utils/loggers/__init__.py
- tools/train.py
- This PR moves the logging info from `train.py` to the corresponding getter functions. This way, `train.py` entrypoint looks cleaner. Also, everytime the getter functions are called, the loggers log the information.
> 🚚 Move logging from train.py to the getter functions

- anomalib/models/cflow/lightning_model.py
- anomalib/models/fastflow/__init__.py
- anomalib/models/fastflow/lightning_model.py
- anomalib/models/fastflow/loss.py
- anomalib/models/fastflow/torch_model.py
- anomalib/models/ganomaly/config.yaml
- anomalib/models/ganomaly/lightning_model.py
- anomalib/models/ganomaly/loss.py
- anomalib/models/ganomaly/torch_model.py
- anomalib/models/stfpm/lightning_model.py
- anomalib/models/stfpm/loss.py
- anomalib/models/stfpm/torch_model.py
- Refactor the loss computation, see #351 for more details
- Fixes https://github.com/openvinotoolkit/anomalib/issues/351
> 🚜 Refactor loss computation

- anomalib/models/dfkde/config.yaml
- anomalib/models/dfm/config.yaml
- anomalib/models/ganomaly/config.yaml
- Currently classification models has `log_images_to: ["local"]` option in the config files. This is a bug since the classification models do not produce anomaly maps to log. This PR fixes this by changing this configuration to `log_images_to: []`. 
- Fixes #371
> 🛠  Fix configs to remove logging heatmaps from classification models.

- requirements/base.txt
Torchvision 0.13.0 ends up installing torch 0.12.0 which leads to segmentation fault in OpenVINO (2022.1.0) inferencer. This PR fixes the versions.
> Fix torchvision version

- setup.py
> When trying to install anomalib locally, as described in the readme.md, using pip install -e ., the command fails.
This happens, because in setup.py, the content of the readme is read into the LONG_DESCRIPTION, without specifying the encoding used.
- Fixes #407
> Add encoding to LONG_DESCRIPTION in setup.py

- anomalib/post_processing/visualizer.py
- Summary of modifications:
- Fix #414 by checking on `self.gt_mask` instead of `self.pred_mask`
- Fix #415 by shifting color-conversions to the two methods which use `cv2`, i.e. `Visualizer.show` and `Visualizer.save`
- Fixes the following two issues
- #414
- #415
> Fix visualization

- anomalib/models/stfpm/lightning_model.py
- Currently the loss in STFPM is computed as follows : `loss = self.loss_val + self.loss(teacher_features, student_features)`. However, `self.loss_val` is always zero and adds no value. This PR therefore removes it from the computation.
- Fixes #421
> Remove the redundant `loss_val`

- README.md
- docs/source/guides/inference.rst
- tools/inference/gradio_inference.py
- Add documentation for Gradio inference.
- Fixes #341
> 📃 Add documentation for gradio inference

- anomalib/models/cflow/config.yaml
- anomalib/models/cflow/lightning_model.py
- anomalib/models/cflow/torch_model.py
- anomalib/models/dfkde/config.yaml
- anomalib/models/dfkde/lightning_model.py
- anomalib/models/dfkde/torch_model.py
- anomalib/models/dfm/config.yaml
- anomalib/models/dfm/lightning_model.py
- anomalib/models/dfm/torch_model.py
- anomalib/models/fastflow/config.yaml
- anomalib/models/fastflow/lightning_model.py
- anomalib/models/fastflow/torch_model.py
- anomalib/models/padim/config.yaml
- anomalib/models/padim/lightning_model.py
- anomalib/models/padim/torch_model.py
- anomalib/models/patchcore/config.yaml
- anomalib/models/patchcore/lightning_model.py
- anomalib/models/patchcore/torch_model.py
- anomalib/models/reverse_distillation/config.yaml
- anomalib/models/reverse_distillation/lightning_model.py
- anomalib/models/reverse_distillation/torch_model.py
- configs/model/cflow.yaml
- configs/model/dfkde.yaml
- configs/model/dfm.yaml
- configs/model/fastflow.yaml
- configs/model/padim.yaml
- configs/model/patchcore.yaml
- configs/model/reverse_distillation.yaml
- configs/model/stfpm.yaml
As per the request in #381
> I work in a production environment with no internet access at runtime and i'm loading weights from a file.
when initializing a FeaturExtractor it in turn loads a model with a hard coded argument pretrained=True, so it attempts to download the model weights.
specifically i'm looking at this line but it pops up in a few places:
`self.feature_extractor = FeatureExtractor(backbone=_backbone(pretrained=True), layers=["avgpool"]).eval()`
- Fixes #381
> Add `pre_train` as a configurable parameter

- anomalib/models/dfkde/config.yaml
- anomalib/models/dfkde/torch_model.py
- anomalib/models/dfm/config.yaml
- This PR fixes dfm and dfkde configs, which currently fails due to trying to saving anomaly_maps. We will need to address VisualizerCallback in a follow up PR to properly handle classification task. 
- Fixes #325
> 🛠 Fix config files and refactor dfkde

- anomalib/data/utils/split.py
> Fix: data split issue

- anomalib/data/utils/split.py
- checking `if seed` for None fails if value of seed is 0. This PR changes that line.
> 🐞 Change if statement

- anomalib/post_processing/visualizer.py
- tests/helpers/model.py
- tests/pre_merge/post_processing/test_visualizer.py
- Fix Visualizer for AD-only methods by referring to `image_result.image` instead of `image_result.heat_map` for `task==classification` since AD-only methods don't produce heat-maps.
- Add integration test for `AnomalyModule`/`Visualizer`, where we test that both AD-only and segmentation modules work with Visualizers in all combinations of `task` and `mode`
- Fixes #441
> Fix visualizer for `classification`, `mode=simple`

- .gitattributes
- Currently GitHub misdetects the repo language as Jupyter Notebook. This PR ignores ipynb files to be scanned by the Linguist library.
> Ignore ipynb files to detect the repo language

- .pre-commit-config.yaml
- pyproject.toml
- tox.ini
- Currently linter configuration are stored in `tox.ini`. This PR moves these configurations to `pyproject.toml` to separate the responsibilities of these two files. `tox.ini` will now handle the test automation, while `pyproject.toml` will sort out setup and configuration.
> Move configuration from tox to pyproject

- .github/workflows/docs.yml
- .github/workflows/nightly.yml
- .github/workflows/pre_merge.yml
- README.md
- This PR adds codacy code grade badge to the readme file.
> Add codacy badge to readme

- anomalib/deploy/inferencers/torch_inferencer.py
- anomalib/post_processing/normalization/min_max.py
- This PR fixes a bug in the inferencer that is caused by tensor->numpy conversion and float type.
- Fixes #473
> 🐞 🛠 Bug fix in the inferencer

- Dockerfile
- requirements/dev.txt
1. Install `nodejs npm ruby` (first two required by prettier hook, last one required by markdownlint)
2. Readd `./requirements/dev.txt` with appropriate packages needed for development and used by vs code via `.devconatiner/devcontainer.json`
- Fixes #477 (issue)
> Fix Dockerfile

- anomalib/models/dfkde/config.yaml
- anomalib/models/dfkde/lightning_model.py
- anomalib/models/dfkde/torch_model.py
- configs/model/dfkde.yaml
Slight refactor of the DFKDE model to accept from the config file the name of the layer needed. Currently this is hard coded to `avgpool` but to be consistent with other models will need to make this configurable.
> DFKDE refactor to accept any layer name like other models

- tools/benchmarking/benchmark.py
- tools/benchmarking/utils/metrics.py
- Benchmarking script now stores results in a sub folder rather than `runs`.
> 🐞 Log benchmarking results in sub folder

- anomalib/models/draem/utils/augmenter.py
- Perlin noise augmentation for DRAEM was instable for image sizes that were not a power of 2. This PR adds a quick fix for this issue by generating the Perlin noise mask with a dimensionality equal to the nearest power of 2 and then cropping back to the original image size.
- This temporarily fixes the issues with DRAEM until we create our own implementation of Perlin noise.
> fix Perlin augmenter for non divisible image sizes

- anomalib/models/draem/config.yaml
- Quick PR to update the default parameter settings for DRAEM
> change default parameter values for DRAEM

- anomalib/utils/metrics/adaptive_threshold.py
- anomalib/utils/metrics/optimal_f1.py
- Adds `reset` method to metrics as suggested in issue #457
> Add reset methods to metrics

- anomalib/models/cflow/anomaly_map.py
- anomalib/models/fastflow/anomaly_map.py
- anomalib/models/padim/anomaly_map.py
- anomalib/models/reverse_distillation/anomaly_map.py
- anomalib/models/stfpm/anomaly_map.py
- tests/helpers/dataset.py
- tests/pre_merge/utils/callbacks/visualizer_callback/dummy_lightning_model.py
- This refactor converts `AnomalyMapGenerator` to `nn.Module`
> Convert `AnomalyMapGenerator` to `nn.Module`

- .github/workflows/pre_merge.yml
- README.md
- Add coverage reporter to CI
- I am not sure how this will behave in `main` branch.
> Add coverage

- anomalib/deploy/optimize.py
- anomalib/models/components/base/anomaly_module.py
- anomalib/utils/callbacks/cdf_normalization.py
- anomalib/utils/callbacks/min_max_normalization.py
- anomalib/utils/sweep/__init__.py
- anomalib/utils/sweep/helpers/__init__.py
- anomalib/utils/sweep/helpers/inference.py
- tests/helpers/inference.py
- tests/pre_merge/deploy/test_inferencer.py
- tools/benchmarking/benchmark.py
- Use a single placeholder for normalization metrics
> 🛠 Refactor Normalization

- anomalib/utils/callbacks/__init__.py
- anomalib/utils/callbacks/metrics_configuration.py
- anomalib/utils/cli/cli.py
- This PR makes sure that validation/testing does not fail when pixel metrics are requested in a classification task. Instead, the metrics configuration callback will ignore the pixel metrics and show a warning to the user.
- Fixes https://github.com/openvinotoolkit/anomalib/issues/513
> Ignore pixel metrics in classification task

- docs/source/guides/export.rst
- Update the export guide to accommodate the latest changes to the export configuration.
> Update export documentation

- anomalib/models/padim/lightning_model.py
PaDim did not use 'pre_trained' value in config.yaml. This PR fixes it.
> FIX: PaDiM didn't use config.model.pre_trained.

- anomalib/models/components/base/anomaly_module.py
- anomalib/utils/metrics/adaptive_threshold.py
- Add call to `reset` method of AdaptiveThreshold metrics. This makes sure that the targets and predictions of previous epochs are cleared before computing the threshold.
- `AdaptiveThreshold` class now inherits from `PrecisionRecallCurve` to prevent having to re-implement `update` and `reset` methods.
- Fixes https://github.com/openvinotoolkit/anomalib/issues/457
> Reset adaptive threshold between epochs

- anomalib/models/components/base/anomaly_module.py
- Loads the correct normalization method from anomaly module whenever the model weights are loaded before the normalization callback is called.
- Proposal to address #523
> 🐞 Set normalization method from anomaly module

- anomalib/utils/callbacks/graph.py
- anomalib/utils/loggers/__init__.py
- anomalib/utils/loggers/comet.py
- docs/blog/001-train-custom-dataset/README.md
- tests/pre_merge/utils/loggers/test_get_logger.py
> 🐞 Fix linting issues

- anomalib/models/patchcore/anomaly_map.py
For images with large defects, the anomaly score of the patchcore method is  sometimes nan in the actual version. This is due to the formula used to compute it,  that involves torch.exp. To remedy this, one can replace the actual computation with a softmax that is more stable numerically and is able to deal with large values. This replacement is only correct and equivalent to the previous formula because the confidence tensor is of shape (1,N), N being the nearest neighbors.
- Fixes #324
> 🐞 Bug Fix: Solve NaN values of anomaly scores for PatchCore model

- anomalib/models/components/base/anomaly_module.py
you have to reutrn the results of load_state_dict if you wrappered the original one
> reutrn results of load_state_dict func

- anomalib/models/cflow/lightning_model.py
- anomalib/models/dfkde/lightning_model.py
- anomalib/models/dfm/lightning_model.py
- anomalib/models/fastflow/lightning_model.py
- anomalib/models/patchcore/lightning_model.py
- anomalib/models/reverse_distillation/lightning_model.py
- Following #514, this PR adds `pre_trained` parameter to `ModelLightning` implementation.
> 🔨 Pass `pre-trained` from config to `ModelLightning`

- anomalib/utils/callbacks/model_loader.py
- This PR adds map_location when loading weights. This is because the current approach does not consider the case where a model is trained on gpu and tested on cpu, or vice-versa.
- Fixes #532
> Add map_location when loading the weights

- requirements/base.txt
- tests/pre_merge/deploy/test_inferencer.py
We had limited torchvision to 0.12.0 because it ended up installing torch 1.12.0. (PR https://github.com/openvinotoolkit/anomalib/pull/396). From my experiments right now everything seems to be working. The tests pass locally. So hopefully this should address patchcore onnx export (https://github.com/openvinotoolkit/anomalib/issues/440) for those using torch==1.12.0
> Add patchcore to openvino export test + upgrade lightning

- anomalib/models/patchcore/anomaly_map.py
- anomalib/models/patchcore/lightning_model.py
- anomalib/models/patchcore/torch_model.py
- This PR fixes the incorrect image-level anomaly score computation of PatchCore. Also fixes the issue that test batch sizes bigger than 1 were not supported.
- Fixes https://github.com/openvinotoolkit/anomalib/issues/286, https://github.com/openvinotoolkit/anomalib/issues/268, #533
> Fix patchcore image-level score computation

- anomalib/models/cflow/anomaly_map.py
- Anomaly map computation in CFlow is incorrect when the batch size is 1. 
- Fixes #450 #568.
> Fix anomaly map computation in CFlow when batch size is 1.

- docs/source/how_to_guides/index.rst
- notebooks/300_benchmarking/302_hpo_wandb.ipynb
- notebooks/README.md
- Add notebook for hpo
- Fixes #254
> ✨ Add notebook for hpo

- anomalib/utils/sweep/config.py
- docs/source/tutorials/benchmarking.rst
- tests/pre_merge/utils/sweep/__init__.py
- tests/pre_merge/utils/sweep/test_config.py
- Replacing keys from benchmarking script will help set dataset from the run configuration. This ensures that all models have the same parameters for dataset.
- Fixes #300
> ✨ Replace keys from benchmarking script

- anomalib/pre_processing/transforms/custom.py
Denormalize is no longer used and will be removed in future version. This PR adds the deprecation warning.
> add deprecation warning to denormalize class

- anomalib/deploy/optimize.py
Create meta_data.json with ONNX export as well as OpenVINO export . This is used to solve OpenVINO version mismatches by exporting the ONNX model in preferred version is required by the users' application.
- Fixes #638 
- [NA] I have added tests that prove my fix is effective or that my feature works
> Create meta_data.json with ONNX export as well as OpenVINO export 

- anomalib/models/patchcore/torch_model.py
results inferenced with onnx is inconsistent with torch, especially the border.
- fix c++ inference with onnx.
before this PR, out:
after this PR, out:
> Optimized inference with onnx for patchcore.

- anomalib/utils/callbacks/__init__.py
- anomalib/utils/callbacks/metrics_configuration.py
- anomalib/utils/metrics/__init__.py
- docs/source/reference_guide/api/metrics.rst
- tests/helpers/dummy.py
- tests/helpers/metrics.py
- tests/pre_merge/utils/callbacks/metrics_configuration_callback/data/config-good-00.yaml
- tests/pre_merge/utils/callbacks/metrics_configuration_callback/data/config-good-01.yaml
- tests/pre_merge/utils/callbacks/metrics_configuration_callback/test_metrics_configuration_callback.py
- tests/pre_merge/utils/callbacks/visualizer_callback/dummy_lightning_model.py
- tests/pre_merge/utils/callbacks/visualizer_callback/test_visualizer.py
> add option to load metrics with kwargs

- tox.ini
Can we do this, please?
It allows one to pass command line arguments to tox while keeping the previous behaviour as default.
Source: [https://stackoverflow.com/a/35287375/9582881](https://stackoverflow.com/a/35287375/9582881)
So `tox -e pre_merge` will run all the tests in `tests/pre_merge`, like currently.
And `tox -e pre_merge tests/pre_merge/path/to/single/test_single.py` will only run the tests in `test_single.py`.
> make it possible to use tox pre_merge to test single file

- anomalib/models/components/feature_extractors/feature_extractor.py
- anomalib/models/stfpm/torch_model.py
- Add eval to feture extractor and use torch.no_grad
- Fixes inconsistent performance between runs
> 🐞Patch Timm Feature Extractor

- anomalib/data/folder.py
PR #660 introduced a check to ensure mask paths are correct. However, this check is also done even if `mask_dir` is not provided. This causes an error for classification tasks, where a mask path is not given.
> 🐞 Fix folder dataset for classification tasks

- docs/source/how_to_guides/index.rst
- notebooks/100_datamodules/104_tiling.ipynb
- This PR adds tiling notebook to both notebooks and docs directories. Despite the support, it was not documented before.
> Add tiling notebook

- anomalib/deploy/inferencers/openvino_inferencer.py
- docs/source/tutorials/inference.rst
- tools/inference/openvino_inference.py
- This PR exposes the device setting to the OpenVINO inference entrypoint script.
> make device configurable in OpenVINO inference

- anomalib/config/config.py
- anomalib/data/__init__.py
- anomalib/data/avenue.py
- anomalib/data/base/datamodule.py
- anomalib/data/btech.py
- anomalib/data/folder.py
- anomalib/data/mvtec.py
- anomalib/data/ucsd_ped.py
- anomalib/models/cflow/config.yaml
- anomalib/models/dfkde/config.yaml
- anomalib/models/dfm/config.yaml
- anomalib/models/draem/config.yaml
- anomalib/models/fastflow/config.yaml
- anomalib/models/ganomaly/config.yaml
- anomalib/models/padim/config.yaml
- anomalib/models/patchcore/config.yaml
- anomalib/models/reverse_distillation/config.yaml
- anomalib/models/stfpm/config.yaml
- tests/pre_merge/datasets/test_datamodule.py
- This PR makes the val/test split ratio configurable from the `config.yaml` (see #731, previously it was hardcoded as 0.5).
- The parameter `val_split_ratio` was added to the base datamodules class and subclasses.
- To avoid confusion with the newly added parameter, the `split_ratio` parameter that determines the fraction of normal images to be used for testing in the Folder dataset, was renamed to `normal_split_ratio`.
- `config.yaml` was updated for the different models.
- also adds `seed` parameter to Avenue and UCSDped datasets, which was missing by mistake.
- Fixes #731
> make val split ratio configurable

- anomalib/config/config.py
Update the deprecation messages related to the datamodules refactor. Remove any references to specific version numbers.
> [Datamodules] Update deprecation messages

- anomalib/config/config.py
- tools/hpo/sweep.py
- tools/train.py
- This pull request changes the behavior when the random number seed is set to 0.
- In the current implementation, when the `config.project.seed` is set to 0, the seed value is not fixed to zero but randomized. After merging this pull request, when the `config.project.seed` is set to 0, the seed value is set to 0.
- A seed can be randomized by either removing the `seed` key from the YAML file or using `None` as the seed value (`null` in the YAML file).
- A warning message is generated when the seed value of 0 is used.
- Fixes #763.
It would be great to get feedback on my warning message because I am not a native English speaker.
> Fix zero seed

- README.md
> Add section for community project

- docs/source/how_to_guides/index.rst
- notebooks/400_openvino/nncf.ipynb
- This PR adds NNCF notebook to both `notebooks` and `docs` directories. Despite the support, it was not documented before.
> Add NNCF notebook to both `notebooks` and `docs`

- anomalib/utils/callbacks/__init__.py
- anomalib/utils/callbacks/model_loader.py
- docs/source/tutorials/inference.rst
- This PR makes a few small changes which allows users to set a manual threshold when running lightning inference, even after the model has been trained with adaptive thresholding enabled. To use the manual threshold, the user can simply set the thresholding method to `manual` in the config, and specify the image and pixel-level thresholds. These values will then overwrite the adaptive threshold values which are loaded from the model weights.
- The model loading functionality in LoadModelCallback was moved from `on_test_start` and `on_predict_start`, which removes duplication and is more in line with the intended use of `setup`.
- By adding the model loader callback before the post-processing configuration callbacks, the threshold value is first loaded from the model file. Then, when …
> Allow setting manual threshold in PL inference

- CHANGELOG.md
- anomalib/models/patchcore/torch_model.py
This reverts commit e965c8a69259eb5b91c876068233f9b9a65ecf5f.
- Reverts a recent change to the Average Pooling layer of PatchCore model which caused the performance deterioration reported by some users in https://github.com/openvinotoolkit/anomalib/issues/715
- Fixes https://github.com/openvinotoolkit/anomalib/issues/715
> Revert "Optimized inference with onnx for patchcore. (#652)"

- CHANGELOG.md
- anomalib/utils/metrics/optimal_f1.py
- Quick PR to deprecate OptimalF1 metric, which has not been used in recent releases since we switched to a dedicated threshold metric class.
> Deprecate OptimalF1 metric

- anomalib/config/config.py
- anomalib/data/folder.py
- tests/pre_merge/datasets/test_datamodule.py
- This PR fixes two bugs on the datamodules branch that were discovered after manual testing. Both are related to the parsing of the Folder dataset format.
- The dataset would throw an error when mask_dir was left empty in classification mode. This was solved by setting an empty mask_path when the samples dataframe is created.
- The deprecation of `dataset.path` in favor of `dataset.root` was not handled correctly (the config update was copied too quickly from the `mask` vs `mask_dir` deprecation).
> Bugfixes for Datamodules feature branch

- anomalib/models/components/base/anomaly_module.py
Another fix for the datamodules feature branch. This one is related to the detection task. Previously the code responsible for obtaining an image score from the bbox scores for a given image was broken. The code assumed that bbox detections were always present in each image. An empty list of bboxes would lead to an error. This PR fixes the issue by setting the score to 0 when no bbox detections are present in the image.
> [Datamodules] Fix bug in bbox score to image score conversion

- anomalib/config/config.py
- anomalib/data/base/datamodule.py
- tools/train.py
Fix for another problem that came up during manual testing of the datamodules branch. The `none` option for `test_split_mode` and `val_split_mode` was not handled properly.
- Prevents sampling normal images from train set to test set when the default test set does not contain normals and `test_split_mode` is `none`.
- Ensures that `limit_val_batches` is set to 0.0 when `val_split_mode` is `none`, to prevent the trainer from trying to run validation on a non-existing validation set.
- `from_test` and `same_as_test` not allowed for `val_split_mode` when test_split_mode is `none` to prevent sampling from non-existing test set.
- Using `test_split_mode` to determine if trainer should test after training.
> Improve handling of `test_split_mode='none'` and `val_split_mode='none'`

- CHANGELOG.md
- anomalib/models/cflow/lightning_model.py
- anomalib/models/draem/lightning_model.py
- anomalib/models/fastflow/lightning_model.py
- anomalib/models/ganomaly/lightning_model.py
- anomalib/models/reverse_distillation/lightning_model.py
- anomalib/models/stfpm/lightning_model.py
- Log loss to the loggers for trainable models.
Note: A logger has to be specified from the config.
> Add loss logging to trainable models

- CHANGELOG.md
- anomalib/models/csflow/lightning_model.py
- Small patch to add early stopping to csflow
> 🩹 Add early stopping to csflow

- anomalib/data/base/dataset.py
- anomalib/data/base/video.py
- anomalib/data/utils/boxes.py
- anomalib/deploy/inferencers/torch_inferencer.py
- anomalib/models/components/base/anomaly_module.py
- tests/pre_merge/datasets/test_bounding_box_utils.py
Small PR that adds an anomaly score for bounding boxes generated from anomaly maps, which is needed for the OTX task.
- Extends `masks_to_boxes` to take anomaly maps as optional additional input, and compute an anomaly score for each bounding box as the max value of the anomaly map within the pixel region covered by the bounding box.
- Update the logic in `AnomalyModule`.
> [Detection] Compute box score when generating boxes from masks

- CHANGELOG.md
- anomalib/data/mvtec.py
- anomalib/data/utils/download.py
- Fixes bug in MVTec dataset download caused by file name missing from the download url.
- Fixes https://github.com/openvinotoolkit/anomalib/issues/835
> fix mvtec download path

- anomalib/post_processing/visualizer.py
Crashes if using version of numpy > 1.23.1 (tested on 1.24.1)
> Remove deprecated usage of np.bool

- .github/workflows/docs.yml
- Since nbsphinx runs the notebooks, it uses the local dataset path. This is because only the tests get path either locally or from the environment variable. This PR links the dataset path from the environment variable to the local folder.
- This works: https://github.com/openvinotoolkit/anomalib/actions/runs/4042706269/jobs/6950734804. The issue was that we have disabled write permissions so this workflow explicitly enables it for this job.
> Link dataset path locally in workflow

- anomalib/data/utils/image.py
This fixes a regression in `get_image_filenames()` caused by changing from a len(image_filenames) == 0 check in a previous commit. Empty lists report as `False`, not `True`, as caught by this, so added a `not` to fix.
> Fix minor logic bug detecting empty list of images

- anomalib/data/avenue.py
- anomalib/data/base/dataset.py
- anomalib/data/btech.py
- anomalib/data/mvtec.py
- anomalib/data/shanghaitech.py
- anomalib/data/ucsd_ped.py
- anomalib/data/visa.py
- Change the type of `root` variable from `str` to `str | Path`.
- With this change, it will be easier to pass `Path` objects when using datamodules via the API.
> Changed the type of root in data modules

- .github/workflows/pre_merge.yml
- README.md
- Replaced coverage reporting tool from Codacy to Codecov for the pre-merge job in the workflow
> [CI] Update coverage tool to codecov for pre-merge

- .github/workflows/pre_merge.yml
- anomalib/utils/loggers/comet.py
- anomalib/utils/loggers/tensorboard.py
- anomalib/utils/loggers/wandb.py
- requirements/base.txt
- requirements/extras.txt
- setup.py
- tests/pre_merge/utils/loggers/test_get_logger.py
- tox.ini
- Move extra requirements to extras.txt
- Check in each logger
> 🩹 Patch requirements

- .ci/README.md
- We don't need to pass token as it is not being used by the ci
> Remove codacy from ci docs

- .pre-commit-config.yaml
- anomalib/data/utils/augmenter.py
- anomalib/deploy/inferencers/torch_inferencer.py
- anomalib/models/csflow/torch_model.py
- anomalib/models/fastflow/loss.py
- anomalib/models/ganomaly/lightning_model.py
- anomalib/models/rkde/region_extractor.py
- anomalib/pre_processing/tiler.py
- anomalib/utils/callbacks/nncf/utils.py
- anomalib/utils/metrics/aupro.py
- pyproject.toml
- requirements/dev.txt
- tests/helpers/aupro_reference.py
- tools/inference/gradio_inference.py
- Add ruff as the main linter
- Remove isort, flake8, pylint and pydocstyle
- Update the pre-commit versions.
- Remove redundant packages from `requirements/dev.txt`
> Add ruff as the main linter

- anomalib/models/components/feature_extractors/torchfx.py
- tests/pre_merge/models/test_feature_extractor.py
Fix code logic to allow for passing of `nn.Module` to  `TorchFXFeatureExtractor`
- Fixes #933
> Bugfix code logic to allow for passing of `nn.Module` to  `TorchFXFeatureExtractor`

- .ci/README.md
- .ci/cuda10.2.Dockerfile
- .ci/cuda11.4.Dockerfile
- The docker files install the latest stable version of nodejs.
- Readme updated to add missing `run.sh` command.
> 🐳 Update Containers and Readme

- README.md
I fixed links in the readme that were not working. 
* Most of them were broken due to move of `anomalib` into `src` directory.
* There was also a link to hardware section of the documentation that no longer exists so I changed that as well.
* Since some of the links were relative and some used entire url, I also unified them all to be relative if referring to the file from the repository.
> Fixed outdated info in readme

- src/anomalib/utils/metrics/aupr.py
This PR mirrors the changes in #944 and #945 , apply for AUPR metric.
> always reorder for aupr metric

- tools/inference/gradio_inference.py
Fixed OpenVINOInferencer instantiation in gradio_inference. OpenVINOInferencer now no longer takes config parameter. This was previously fixed in openvino_inference, but not in gradio_inference, so I fixed it here as well.
- Fixes #971
> Fixed openvino_inferencer in gradio_inference

- .pre-commit-config.yaml
> enable auto-fixing for ruff in pre-commit

- .ci/cuda11.4.Dockerfile
Here is a proposed fix to a bug I've been encountering. Right off the bat, I have not created an issue on GitHub corresponding to my problem, but I can do it if needed.
Issue : VSCode throwing following error while building Anomalib container :
```
> [python_base_cuda11.4 7/7] RUN curl -sL https://deb.nodesource.com/setup_current.x > nodesetup.sh &&     bash - nodesetup.sh &&     apt-get install --no-install-recommends -y nodejs &&     apt-get clean &&     rm -rf /var/lib/apt/lists/*:
#0 0.277 /bin/sh: 1: cannot create nodesetup.sh: Permission denied 
``` 
This error occurred on two separate computers, including one where I never installed Anomalib (so it couldn't be linked to cached container issues)
Steps to reproduce :
- Clone anomalib locally
- Open anomalib folder with VSCode
- …
> Cuda 11.4 dockerfile fix

- CHANGELOG.md
- src/anomalib/data/base/video.py
- src/anomalib/post_processing/visualizer.py
- tests/pre_merge/datasets/test_video.py
- In multi-frame video pipelines, we need to set which frame acts as the reference frame, meaning the ground truth information of that frame will be used to represent the (multi-frame) video clip.
- This PR makes this configurable from the config. The user may elect to take the GT info from the first frame, last frame, mid frame or all frames combined.
> Configure reference frame for multi-frame video clips

- MANIFEST.in
This PR aims to make anomalib PEP 561 compliant for mypy:
1. Add py.typed file in package directory.
2. Include py.typed in MANIFEST.in.
reference:
https://mypy.readthedocs.io/en/stable/installed_packages.html#creating-pep-561-compatible-packages
If we have a `test_mypy.py` for testing with the following content:
`
from anomalib.config import get_configurable_parameters, update_nncf_config
`
Before this PR, when running: `mypy test_pep561.py`, it will generate the following error.
```
test_pep561.py:1: error: Skipping analyzing "anomalib.config": module is installed, but missing library stubs or py.typed marker  [import]
test_pep561.py:1: note: …
```
> Make anomalib PEP 561 compliant for mypy

- notebooks/000_getting_started/001_getting_started.ipynb
- src/anomalib/models/components/layers/sspcab.py
[Bug: 865] datamodule.setup() assertion failed
This fix download the dataset first before splitting the train/val/test sets.
- Fixes #865
> [Bug: 865] datamodule.setup() assertion failed

- src/anomalib/data/__init__.py
- src/anomalib/data/btech.py
- src/anomalib/data/folder.py
- src/anomalib/data/folder_3d.py
- src/anomalib/data/mvtec.py
- src/anomalib/data/mvtec_3d.py
- src/anomalib/data/utils/__init__.py
- src/anomalib/data/utils/label.py
- src/anomalib/data/utils/path.py
- src/anomalib/models/reverse_distillation/anomaly_map.py
- src/anomalib/models/reverse_distillation/lightning_model.py
- src/anomalib/models/reverse_distillation/torch_model.py
- src/anomalib/post_processing/__init__.py
- src/anomalib/post_processing/visualizer.py
- src/anomalib/pre_processing/__init__.py
- src/anomalib/pre_processing/tiler.py
- src/anomalib/utils/callbacks/tiler_configuration.py
- src/anomalib/utils/callbacks/visualizer/visualizer_base.py
- tests/pre_merge/datasets/test_dataset.py
Code refactor: add the following types to replace original string constants.
- LabelType,
- DirType,
- SupportedDataType
- AnomalyMapGenerationMode
- UpscaleImageMode
- VisualizeMode
- Fixes #644
> Refactor strings and ints into enum.Enum

- .github/workflows/pre_merge.yml
- Removed the `-Z` flag as it fails the CI if codecov upload fails
- Don't pass token if it is not passed to the action.
> Modify codecov upload

- setup.py
With this PR, when running 
`python setup.py install`, `python setup.py install sdist` or `python setup.py sdist bdist_wheel`, `py.typed` will be included in the build package.
- Fixes #1015
> Fix mypy pep561

- .ci/trivy.yaml
- .github/workflows/code_scan.yml
- tox.ini
Updated code-scan workflow to use Trivy instead of SNYK
> Update code-scan workflow to use Trivy

- CHANGELOG.md
- notebooks/000_getting_started/001_getting_started.ipynb
- pyproject.toml
- src/anomalib/__init__.py
- src/anomalib/deploy/inferencers/openvino_inferencer.py
- src/anomalib/utils/callbacks/nncf/callback.py
- src/anomalib/utils/sweep/helpers/inference.py
- tools/inference/gradio_inference.py
- tools/inference/openvino_inference.py
- Fixes init_state_dict in nncf
- Pass medatata as a dict to OpenVINO inferencer
> Patch release 0.5.1

- .ci/README.md
- .github/workflows/pre_merge.yml
- Workaround to accessing secrets from fork is to use environment variable in the CI. After updating the CI, this PR uses the environment variable as a fallback
> Pass codedov token from environment

- src/anomalib/models/fastflow/torch_model.py
> Fix Fastflow ONNX export.

- src/anomalib/deploy/export.py
- Fixes #1158 by casting to a type expected by `torch.onnx.export`
No clue why mypy doesn't detect this though, and the type-error is caught only at run-time.
> Fix typechecking error for toch.onnx.export

- pyproject.toml
- requirements/loggers.txt
- src/anomalib/utils/hpo/runners.py
- src/anomalib/utils/sweep/__init__.py
- src/anomalib/utils/sweep/utils.py
- tools/benchmarking/benchmark.py
- tools/benchmarking/utils/__init__.py
- tools/benchmarking/utils/metrics.py
- While this started as an exercise to simplify the script, it probably has become more complicated. But the outputs look pretty now 🤷‍♂️
- All outputs are logged to `runs/benchmark.logs`.
- I've removed throughput computations as it needs to be rafactored and we don't use it anywhere.
- Also, I've tried to ensure that any exception does not break the benchmarking run so that the script keeps collecting results for the models that work.
> **Note:** wandb and comet uploads haven't been tested yet
> 🚚 Refactor Benchmarking Script

- CHANGELOG.md
- src/anomalib/data/mvtec.py
- Ignore the image-path mask-path check in the MVTec sample collection when no anomalous samples are available. This ensures that the dataset and datamodule can be created when only normal samples are available in the directory structure.
- Fixes https://github.com/openvinotoolkit/anomalib/issues/1238
> Enable training with only normal images for MVTec

- src/anomalib/utils/callbacks/graph.py
> Wandb unwatch method belongs to experiment, not logger

- src/anomalib/models/components/feature_extractors/torchfx.py
Currently the usage of specific feature extractors with custom layers, some of which might be problematic to the torch tracer is not possible (check [example in the pytorch documentation](https://pytorch.org/vision/main/generated/torchvision.models.feature_extraction.create_feature_extractor.html#create-feature-extractor)). For this to work, I added the tracer_kwargs parameter to the custom "TorchFXFeatureExtractor" class.
> (Minor change) Added the tracer_kwargs to the TorchFXFeatureExtractor class

- src/anomalib/models/patchcore/torch_model.py
This PR replaces torch cdist that causes errors when it's exported to Onnx and OpenVINO. Performance stays the same, as new functions matches cdist in precision up to 10e-7, with small difference occurring due to numerical instability.
- Fixes #967 and #1263
> Replace cdist in Patchcore

- CHANGELOG.md
- docs/source/how_to_guides/train_custom_data.rst
- src/anomalib/data/folder.py
- src/anomalib/models/components/feature_extractors/torchfx.py
- tests/pre_merge/datasets/test_datamodule.py
- Modified the Folder Dataset type to use the ListConfig type to accept paths as a List.
- Add a ListConfig to an existing type with an input of paths it can accept.
- PR for #1195 
```
dataset:
name: model
format: folder
path: /app/data/trainData
normal_dir: [folder1, folder2]
normal_test_dir: [testfolder1, testfolder2]
normal_dir:
- folder1
- folder2
```
> Add support for receiving folder dataset paths as a list

- .github/workflows/publish.yml
- Modifies publish workflow to run when a release is puslished. The problem with create is that if you first save it as a draft then the workflow will not run.
- Adds manual trigger.
> Modify workflow

- README.md
An error occurs because the custom database on README.md does not have four required keys: normalization, val_split_mode, and test_split_mode. 
So I added that key.
> [Chore] Modify README custom dataset 

- .github/workflows/docs.yml
- README.md
- Fix docs build
- Example (https://github.com/ashwinvaidya17/anomalib/actions/runs/6001349893/job/16275342469)
Need to change settings though
> 🩹 Fix docs build

- src/anomalib/utils/metrics/pro.py
- tests/pre_merge/utils/metrics/test_pro.py
Fixes PRO metric calculation on GPU by changing type to float, as well as matches shapes so it works with predictions of shape N, H, W.
I also adjusted tests to verify that it does works with relevant shapes and types.
- Fixes #1316 
<details>
</details>
<details>
</details>
> Fix PRO metric calculation on GPU

- .ci/Dockerfile
Docker fails to run when running from image `nvidia/cuda:11.4.0-devel-ubuntu20.04`. This version does not exist on DockerHub (instead, it is version 11.4.3)
<details>
<summary>Changed cuda version from 11.4.0 to 11.4.3</summary>
</details>
<details>
</details>
> Fix dockerfile cuda version

- requirements/base.txt
Thanks a lot for this project! I've had it on my radar for a while but didn't have a use case for it. let me know if I need to make any changes.
- Include `setuptools` as a base requirment
Usually, this comes with `pip`, but it's possible to have a virtual environment without pip installed. In my case, I'm using `pdm`, which [does not include `pip` in it's virtual environments](https://pdm.fming.dev/latest/usage/venv/#including-pip-in-your-virtual-environment).
At `setuptools==41.0.0`, we get `AttributeError: module 'collections' has no attribute 'MutableMapping'`, as it expects `colllections.abc.MutableMapping`.
You can reproduce it by creating a new project with `pdm` and adding `anomalib`.
This is actually a dependency for `pytorch-lightening`. But since it's restricted to …
> Add `setuptools` as a requirement (via `pkg_resources`)

- src/anomalib/models/patchcore/torch_model.py
Straighforward fix.
- Fixes #1334 
Additionally deal with an edge case where the memory bank ends up being smaller than `num_neighbors` (computation of the image-wise score).
<details>
</details>
<details>
</details>
> Fix patchcore interpolation

- src/anomalib/models/efficient_ad/lightning_model.py
I ran into an OutOfMemory exception when calculating the teacher channel mean and standard deviation while training the EfficientAD model. I fixed this by not saving the teacher outputs to a list but instead iterating the dataloader twice.
- Fixes #1301 
- **TODO**: Sort out pre-commit stuff (couldn't get the pre-commit hooks running)
- Maybe: Implement 'online' mean and variance calculation, see https://github.com/openvinotoolkit/anomalib/issues/1301#issuecomment-1693126642
<details>
</details>
<details>
</details>
> Efficient ad reduced memory footprint

- src/anomalib/deploy/export.py
When exporting to ONNX the models input shape is fixed to a batch-size of 1. This only allows to feed single images into the resuting anomaly model. 
Torch.onnx allows to define dynamic axes when exporting the model, which enables dynamic batch-sizes. 
<details>
</details>
<details>
</details>
> Allow dynamic batch-sizes when exporting to ONNX, instead if fixed input shapes

- src/anomalib/models/components/feature_extractors/timm.py
This PR adds support to loading pretrained backbone weights from a URI in the config.
For example:
```yaml
model:
backbone: resnet18__AT__https://download.pytorch.org/models/resnet18-5c106cde.pth
```
```yaml
model:
backbone: resnet18__AT__file:///home/user.cache/torch/hub/checkpoints/resnet18-5c106cde.pth
```
Caveat: The weight loading may fail quietly because of `strict=False`. Users need to make sure the weight file works for the model.
<details>
</details>
<details>
</details>
> Add support to backbone URI in config.

- docs/source/tutorials/training.rst
- Fixes #1362
<details>
</details>
<details>
</details>
> Update the broken link in training.rst

- src/anomalib/models/efficient_ad/torch_model.py
AutoEncoder in EfficientAD uses both the width and height of the original image for upscaling, and the size of its output matches the output of other models. 
- Fixes #1352,  mentioned in [this comment](https://github.com/openvinotoolkit/anomalib/issues/1352#issuecomment-1731175752),
Training of EfficientAD fails if the input image has a different width and height:
```
File "./anomalib/src/anomalib/models/efficient_ad/torch_model.py", line 322, in forward
distance_ae = torch.pow(teacher_output_aug - ae_output_aug, 2)
RuntimeError: The size of tensor a (56) must match the size of tensor b (120) at non-singleton dimension 3
Epoch 0:   0%|          | 0/215 [00:00<?, ?it/s]  
```
<details>
</details>
<details>
<summary>Ensure that you followed …
> Fix EfficientAD to use width and height of the input

- docs/source/reference_guide/api/metrics.rst
`compute_on_cpu` should be an internal parameter of `init_args` in the `metrics` configurations.
Added indentation so that the format of the config file is right.
<details>
</details>
<details>
</details>
> Missing indentation in metrics.rst docs

- notebooks/100_datamodules/104_tiling.ipynb
- src/anomalib/models/ganomaly/config.yaml
- src/anomalib/pre_processing/tiler.py
- src/anomalib/utils/callbacks/__init__.py
- src/anomalib/utils/callbacks/tiler_configuration.py
Fixes the tiler functionality by adding the `TilerConfigurationCallback` to the list of callbacks if enabled from the config. Also deprecates the random tiling functionality which was broken and rarely used.
<details>
</details>
<details>
</details>
> Address tiler issues

- .pre-commit-config.yaml
- pyproject.toml
Replace `black` with `ruff`. According to the author of ruff, it is 30x faster than black and 99% compatible. As can be seen from the changes, it is indeed compatible in our case. For more details, you could refer to this [link](https://twitter.com/charliermarsh/status/1716861072374657497?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Etweet).
<details>
</details>
<details>
</details>
> Replace black with ruff formatter

- src/anomalib/models/efficient_ad/lightning_model.py
Implemented an iterative algorithm to calculate the per channel mean and std of the teacher model preventing the need for computing the model outputs twice. 
- Fixes #1454
- **TODO:** The algorithm may need further testing
- **TODO:** There may be a way to initialize the algorithm outside of the loop 
<details>
</details>
<details>
</details>
> Improved speed and memory usage of mean+std calculation

- src/anomalib/callbacks/normalization/cdf_normalization.py
Fixes a circular import in CDF normalizer.
Fixed by collecting the normalization stats using a Lightning Trainer instance instead of an Anomalib engine.
<details>
</details>
<details>
</details>
> Fix circular import in cdf normalizer

- src/anomalib/data/depth/folder_3d.py
- src/anomalib/data/depth/mvtec_3d.py
- src/anomalib/data/image/btech.py
- src/anomalib/data/image/folder.py
- src/anomalib/data/image/kolektor.py
When attempting to train via CLI using the default normalization method on certain datasets (btech, kolektor, folder, mvtech_3d, folder_3d), the following error occurs:
```
'IMAGENET' is not a valid InputNormalizationMethod 
```
For example, try executing the following command:
```
anomalib train --model Patchcore --data anomalib.data.Kolektor
```
I changed the order of types from `str | InputNormalizationMethod` to `InputNormalizationMethod | str` to ensure that the default value is interpreted correctly as an instance of the InputNormalizationMethod enum, instead of the string 'IMAGENET'.
- Fixes #1584 
<details>
<summary>Describe the changes you made
</summary>
</details>
<details>
</details>
> [Bug] v1: Fix default input normalization method

- .github/pull_request_template.md
Mirror #1596 for the main branch.
🛠️ Fixes # N/A
> 📚 Modify the PR template

- src/anomalib/models/cfa/README.md
- src/anomalib/models/cflow/README.md
- src/anomalib/models/csflow/README.md
- src/anomalib/models/fastflow/README.md
- src/anomalib/models/padim/README.md
- src/anomalib/models/stfpm/README.md
The sample result images in the README files for several of the models did not display.
The wrong image URLs were corrected. I opted to stick with relative paths as this makes more sense in case of a fork, for example. I did not touch the existing absolute paths.
> Fix result image URLs

- README.md
- src/anomalib/models/efficient_ad/torch_model.py
Fixed shape error, allowing arbitary image sizes for EfficientAD
Adjusted the Decoder Network last layer interpolation in the EfficientAD Autoencoder.
- Fixes #1528 
<details>
<summary>Updated the Decoder network</summary>
- [ x] Bug fix (non-breaking change which fixes an issue)
- [ x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
</details>
<details>
</details>
> Fixed shape error, allowing arbitary image sizes for EfficientAD

- requirements/base.txt
- tests/unit/models/components/clustering/test_gmm.py
- The `test_gmm.py` is flaky as the randomly generated datapoints might end up near the wrong cluster.
In the first image, the colours show the labels expected by the test but from the figure you can see that the clusters are close to the wrong cluster.
The solution is probably too conservative but the new clusters are now separated by a large margin.
> 🐞 Fix GMM test

- docs/source/markdown/guides/reference/models/image/index.md
- docs/source/markdown/guides/reference/models/image/uflow.md
Add missing docs for the U-Flow model
> 📚 Add docs for the U-Flow model

- .pre-commit-config.yaml
- pyproject.toml
- src/anomalib/callbacks/nncf/callback.py
- Add bandit to pre-commit checks to improve the security of the code.
> 🔒 Add bandit checks to pre-commit

- src/anomalib/models/image/efficient_ad/lightning_model.py
- This PR adds guards and modifies code used in EfficientAD scheduler setup to now correctly determine number of steps. It now works regardless of the arguments (max_epochs, max_steps) provided.
- 🛠️ Fixes #1679
> Fix scheduler num_steps for EfficientAD

- docs/source/index.md
- docs/source/markdown/get_started/migration.md
- src/anomalib/cli/cli.py
- src/anomalib/data/utils/transforms.py
- src/anomalib/models/__init__.py
- tests/README.md
- tests/integration/tools/upgrade/expected_draem_v1.yaml
- tests/integration/tools/upgrade/original_draem_v0.yaml
- tests/integration/tools/upgrade/test_config.py
- tests/unit/data/utils/test_transforms.py
- tools/upgrade/__init__.py
- tools/upgrade/config.py
- This is to provide a script to update the anomalib v0.* configuration to the new configuration format. This is also as part of the following best-practices silver badge guideline
> The project MUST maintain the most often used older versions of the product or provide an upgrade path to newer versions. If the upgrade path is difficult, the project MUST document how to perform the upgrade (e.g., the interfaces that have changed and detailed suggested steps to help upgrade).
- Would it be an idea to add this to Anomalib CLI?
For more information about code review checklists, see the [Code Review Checklist](../docs/source/markdown/guides/developer/code_review_c …
> 💥 Create a script to upgrade v0.* configuration format to v1

- src/anomalib/data/base/datamodule.py
- src/anomalib/data/base/video.py
- src/anomalib/models/components/base/anomaly_module.py
- src/anomalib/models/image/winclip/lightning_model.py
Minor change in how we check if `self._setup` should be called in `setup`. The change is repeated in both the datamodule and the anomaly module. This is mainly to ensure that we can use the modules in a standalone fashion, without/before being attached to a trainer. For example, we could use the following to quickly inspect the images in our datamodule.
```python
>>> from anomalib.data import MVTec
>>>
>>> datamodule = MVTec(image_size=(512, 512))
>>> datamodule.setup()
>>>
>>> sample = next(iter(datamodule.train_dataloader()))
>>> sample["image"].shape
torch.Size([32, 3, 512, 512])
```
Similarly, we could inspect the structure of the torch model of a given Lightning model after invoking `setup`:
```python
>>> from anomalib.models import Ganomaly
>>>
>>> model = Ganomaly()
>>> …
```
> Update setup logic in model and datamodule

- tests/unit/engine/test_setup_transform.py
Small PR that adds a testcase to the transform tests.
> Add test case to model transform tests

- src/anomalib/data/utils/path.py
- tests/unit/data/utils/test_image.py
- tests/unit/data/utils/test_path.py
- This is to remove access denied error.
- 🛠️ Fixes #1688 
> 🔨 Remove access denied error

- setup.py
> Hot-fix wrong requirement for setup.py

- CHANGELOG.md
- src/anomalib/data/utils/boxes.py
- Addresses https://github.com/openvinotoolkit/anomalib/issues/1830
> 🐞Fix the error if the device in masks_to_boxes is not both CPU and CUDA

- src/anomalib/data/utils/image.py
Currently, loading grayscale images leads to errors in the visualization callback, because the channels are missing.
This change ensure that images are always loaded as RGB.
Additionally fixes:
- 🛠️ #1831
- [ x ] 🐞 Bug fix (non-breaking change which fixes an issue)
> 🛠️ Ensure images are loaded in RGB format

- src/anomalib/deploy/inferencers/openvino_inferencer.py
Fixed incorrect label assignment.
Was True/False, now it's "Anomalous/Normal" as for the PyTorch inferencer in torch_inferencer.py
> Changed prediction label assignment for OpenVINO inferencer

- pyproject.toml
- src/anomalib/models/components/filters/blur.py
- `get_gaussian_kernel2d` function in kornia returns `1xMxN` kernel in the new version. In the previous versions of kornia, on the other hand, this was `MxN`. This difference causes a dimensionality mismatch issues.
- 🛠️ Fixes #1798 
> 🐞 Fix dimensionality mismatch issue caused by the new kornia version

- pyproject.toml
- src/anomalib/models/image/cflow/lightning_model.py
- src/anomalib/models/image/cflow/torch_model.py
- src/anomalib/models/image/csflow/lightning_model.py
- src/anomalib/models/image/csflow/torch_model.py
- src/anomalib/models/image/fastflow/lightning_model.py
- src/anomalib/models/image/padim/lightning_model.py
- src/anomalib/models/image/padim/torch_model.py
- src/anomalib/models/image/patchcore/lightning_model.py
- src/anomalib/models/image/patchcore/torch_model.py
- src/anomalib/models/image/reverse_distillation/lightning_model.py
- src/anomalib/models/image/stfpm/lightning_model.py
- src/anomalib/models/image/stfpm/torch_model.py
- src/anomalib/models/image/uflow/feature_extraction.py
- src/anomalib/models/image/uflow/torch_model.py
- tests/integration/model/test_models.py
- This PR bumps the torch and lightning versions.
> Update torch and lightning package versions

- src/anomalib/models/components/base/anomaly_module.py
- This PR replaces `@abstractproperty` with `@property` `@abstractmethod` as the former is now deprecated.
> 🔨 Replace `@abstractproperty` since it is deprecated

- src/anomalib/data/utils/tiler.py
- src/anomalib/models/image/padim/torch_model.py
- src/anomalib/models/image/patchcore/torch_model.py
- src/anomalib/models/image/stfpm/torch_model.py
Fixes the problem where shape of anomaly map isn't set correctly in case of tiling.
- 🛠️ Fixes #1958
> Fix anomaly map shape to also work with tiling

- src/anomalib/models/image/efficient_ad/lightning_model.py
- Downloaded and extracted EfficientAD's pretrained models' filenames are "pretrained_teacher_**small**.pth" or "pretrained_teacher_**medium**.pth"
- But, loaded pretrained models' filenames are "pretrained_teacher_**EfficientAdModelSize.S**.pth" or "pretrained_teacher_**EfficientAdModelSize.M**.pth", because of getting load path with string interpolation with model size enum itself.
- Fix load path interpolation to use associated enum value("small" or "medium")
- 🛠️ Fixes #1965 
For more information about code review checklists, see the [Code Review Checklist](https://github.com/openvinotoolkit/anomalib/blob/main/docs/source/markdown/guides/developer/code_re …
> 🐞 Fix EfficientAD's pretrained weigths load path

- src/anomalib/metrics/aupr.py
when I try to use aupr in my program, some error happen as follow:
```sh
File "xxx/envs/anomalib_env/lib/python3.10/site-packages/anomalib/metrics/__init__.py", line 60, in metric_collection_from_names
metrics.add_metrics(metric_cls())
TypeError: PrecisionRecallCurve.__new__() missing 1 required positional argument: 'task'
```
I found that's because PrecisionRecallCurve required positional argument: 'task'. We can use use BinaryPrecisionRecallCurve instead of PrecisionRecallCurve to solve this problem
```
PrecisionRecallCurve
This function is a simple wrapper to get the task specific versions of this metric, which is done by setting the
``task`` argument to either ``'binary'``, ``'multiclass'`` or ``multilabel``. See the documentation of …
```
> fixbug: use BinaryPrecisionRecallCurve instead of PrecisionRecallCurve

- CHANGELOG.md
- docs/source/markdown/guides/reference/data/image/index.md
- docs/source/markdown/guides/reference/data/image/mvtec_loco.md
- src/anomalib/callbacks/metrics.py
- src/anomalib/cli/cli.py
- src/anomalib/data/__init__.py
- src/anomalib/data/base/datamodule.py
- src/anomalib/data/image/__init__.py
- src/anomalib/data/image/mvtec_loco.py
- src/anomalib/data/utils/split.py
- src/anomalib/metrics/__init__.py
- src/anomalib/metrics/collection.py
- src/anomalib/metrics/spro.py
- src/configs/README.md
- src/configs/data/mvtec_loco.yaml
- tests/helpers/data.py
- tests/unit/data/image/test_mvtec_loco.py
- tests/unit/metrics/test_spro.py
This PR is based on the closed PR #1635 , which adds the implementation of MVTec LOCO AD dataset [[Paper](https://link.springer.com/article/10.1007/s11263-022-01578-9#Fn1)] along with the sPRO metric.
🛠️ Fixes #574 #471 #1341 
> 🚀 Add support for MVTec LOCO dataset and sPRO metric

- CHANGELOG.md
- src/anomalib/cli/cli.py
- src/anomalib/engine/engine.py
This PR adds some minor modifications to the lightning inference:
- Adds two properties (`checkpoint_callback` and `best_model_path`) to the engine that help with retrieving the path of the saved checkpoint.
- Adds `data_path` argument to `engine.predict` to allow passing the path to a (folder of) image(s) directly to the entrypoint. This way the user does not need to create a `PredictDataset`.
- Updates the CLI to reflect the API changes.
> 🔨 Update lightning inference

- configs/data/avenue.yaml
- configs/data/btech.yaml
- configs/data/folder.yaml
- configs/data/kolektor.yaml
- configs/data/mvtec.yaml
- configs/data/mvtec_3d.yaml
- configs/data/shanghaitec.yaml
- configs/data/ucsd_ped.yaml
- configs/data/visa.yaml
- 🛠️ Fixes #2031
There is a mismatch between some data config keys and `AnomalibDataModule` [init parameters](https://github.com/openvinotoolkit/anomalib/blob/f396dd4ab6a40b7b2f95004278d328fff18c999e/src/anomalib/data/base/datamodule.py#L78C9-L78C17) for all datasets. 
It looks like `normalization` and `center_crop` were replaced by more general `transform`, `transform_config_train` and `transform_config_eval` were renamed to `train_transform` and `eval_transform`, respectively.
I changed this in all data config files, now it is possible to start the training using these configs.
For more information about code review checklists, see the [Code Review …
> Fixed keys in data configs to fit AnomalibDataModule parameters

- configs/model/efficient_ad.yaml
- src/anomalib/models/image/efficient_ad/README.md
- src/anomalib/models/image/efficient_ad/lightning_model.py
- tests/integration/model/test_models.py
- 🛠️ Fixes #1943
Several changes to fix the performance:
- Replaced teacher weights with the ones from [Nelson1425](https://github.com/nelson1425/EfficientAD), thanks to @alexriedel1 for advice. Renamed layers to match anomalib implementation, new weights can be downloaded [here](https://drive.google.com/file/d/1AWZyFEYpIpGZhv5uArAVkIdCwbcRpr_X/view?usp=sharing).
- Removed Imagenet normalization from transforms for this model, because it is in the `forward` for every submodel already. Added checkup to detect if it is added by the user.
- The `train_batch_size` should be 1, as described in the paper. It seems hard to hardcode because it is used in the `AnomalibDataModule`, which has no access to the model's name, so I have just added a checkup to raise an error if the value is not 1.
- …
> Fix efficient ad

- src/anomalib/models/image/dsr/lightning_model.py
- src/anomalib/models/image/dsr/torch_model.py
- 🛠️ Fixes DSR training when no GPU
> Fixed DSR training when no GPU

- pyproject.toml
- src/anomalib/deploy/export.py
- src/anomalib/loggers/wandb.py
- Upgrade wandb https://github.com/openvinotoolkit/anomalib/pull/1928
- Fixes for logger
> ⬆️ Upgrade wandb

- src/anomalib/engine/engine.py
- src/anomalib/loggers/mlflow.py
- src/anomalib/models/components/sampling/k_center_greedy.py
- src/anomalib/utils/rich.py
- Since coreset subsampling uses `track` from `rich`, it breaks when we use any other progress bar. This caches the `LiveDisplay` before using `track` in subsampling.
> 🐞 Fix Rich Progress with Patchcore Training

- src/anomalib/data/utils/download.py
- Inspired from: [https://vorakl.com/articles/tar-curdir/](https://vorakl.com/articles/tar-curdir/)
- See: [Data Filter](https://docs.python.org/3/library/tarfile.html#tarfile.data_filter)
> Add data filter in tar extract

- docs/source/markdown/guides/reference/models/image/index.md
- docs/source/markdown/guides/reference/pipelines/base/generator.md
- docs/source/markdown/guides/reference/pipelines/base/job.md
- docs/source/markdown/guides/reference/pipelines/base/pipeline.md
- docs/source/markdown/guides/reference/pipelines/benchmark/generator.md
- docs/source/markdown/guides/reference/pipelines/benchmark/index.md
- docs/source/markdown/guides/reference/pipelines/benchmark/job.md
- docs/source/markdown/guides/reference/pipelines/index.md
- docs/source/markdown/guides/reference/pipelines/runners/index.md
- docs/source/markdown/guides/reference/pipelines/runners/parallel.md
- docs/source/markdown/guides/reference/pipelines/runners/serial.md
- docs/source/snippets/pipelines/benchmark/cli_anomalib.txt
- docs/source/snippets/pipelines/benchmark/cli_tools.txt
- src/anomalib/pipelines/components/base/runner.py
> 📚 Add Pipelines Documentation

- CHANGELOG.md
- src/anomalib/engine/engine.py
- src/anomalib/utils/visualization/image.py
- Fix anomaly map normalization when `NormalizationMode` is set to `NONE`
- When dataset-level normalization is disabled, the visualizer should normalize the heatmaps at the image-level.
before
after
> Fix image-level heatmap normalization

- CHANGELOG.md
- pyproject.toml
- src/anomalib/cli/install.py
- src/anomalib/cli/utils/installation.py
- src/anomalib/models/video/ai_vad/clip/clip.py
- tests/unit/cli/test_installation.py
The ``pkg_resources`` module is deprecated and does not export the required symbols in newer versions. It is advised to use ``packaging`` or ``importlib`` instead. Because we only rely on functionality present in ``packaging``, the change from ``pkg_resources`` to ``packaging`` should be straightforward.
- [ x ] 🐞 Bug fix (non-breaking change which fixes an issue)
- [ x ] 📋 I have summarized my changes in the [CHANGELOG](https://github.com/openvinotoolkit/anomalib/blob/main/CHANGELOG.md) and followed the guidelines for my type of change (skip for minor changes, documentation updates, and test enhancements).
- [ - ] 📚 I have made the necessary updates to the …
> Remove pkg_resources imports and use packaging instead

- src/anomalib/models/image/efficient_ad/lightning_model.py
- imprved handling of efficient ad model_size Enum handling
- 🛠️ Fixes #2157 
> fix: efficient ad model_size str fixes

- src/anomalib/loggers/mlflow.py
- In `AnomalibMLFlowLogger`, `tracking_uri` was set to None, which was overriding the parameter in the underlying pytorch `MLFlowLogger` so you could never log in to a remote server. This fixes it.
- 🛠️ Fixes # (NO EXISTING ISSUE YET)
> fix: get MLFLOW_TRACKING_UTI from env variables as default

- src/anomalib/data/depth/folder_3d.py
- fixes: #1826 
Refactored `make_folder_3d_dataset` into three separate functions to improve readability and maintainability:
`make_folder_3d_dataset`: Handles the overall process of generating a 3D dataset by calling `make_path_dir` and `add_mask`.
Since the make_folder_3d_dataset function is only used once in the codebase, this refactoring should not significantly impact the overall structure while enhancing the clarity of the code and remove the ruff C901 error.
> Refactored-make_folder3d_dataset-ruff-error-C901

- .pre-commit-config.yaml
- src/anomalib/callbacks/normalization/min_max_normalization.py
- src/anomalib/deploy/inferencers/base_inferencer.py
- src/anomalib/models/components/base/anomaly_module.py
- src/anomalib/models/image/csflow/lightning_model.py
- src/anomalib/models/image/csflow/torch_model.py
Fixes: https://github.com/openvinotoolkit/anomalib/discussions/2122#discussioncomment-9740488 and https://github.com/openvinotoolkit/anomalib/issues/2027 and https://github.com/openvinotoolkit/anomalib/issues/2139#issue-2352819822
The normalization metrics are resetted before every validation. Is there any flaw in this logic or does it makes sense, so that models that have very different anomaly map and pred score magnitudes during training epochs are optimally normalized.
For more information about code review checklists, see the [Code Review Checklist](https://github.com/openvinotoolkit/anomalib/blob/main/docs/source/markdown/guides/developer/code_review_ch …
> Fix normalization

- src/anomalib/cli/utils/installation.py
- tests/unit/cli/test_installation.py
- Cuda `+cpu`/`+cuda` post-fix to torch requirements fails when we call `anomalib install --option full`
- One discussion on this change is here https://discuss.python.org/t/lets-permit-local-version-label-in-version-specifiers/22781
- From my tests just passing the `extra-index-url` seems to work
- Addresses https://github.com/openvinotoolkit/anomalib/issues/2156
tox.ini
```diff
[tox]
isolated_build = True
skip_missing_interpreters = true
envlist =
pre-commit
pre-merge-py{38,39,310}
snyk-scan
+     install-py{310, 311}
[testenv]
passenv = ftp_proxy
HTTP_PROXY
HTTPS_PROXY
CUDA_VISIBLE_DEVICES
[testenv:pre-commit]
basepython = py310
deps =
pre-commit
commands = pre-commit run --all-files
+ [testenv:install-py{310,311}]
+ commands = 
+     pip install -e .
+     anomalib install --option …
```
> 🔨Remove device postfix

- src/anomalib/callbacks/checkpoint.py
- src/anomalib/data/base/datamodule.py
- src/anomalib/engine/engine.py
- tests/unit/metrics/test_adaptive_threshold.py
The `trainer.model` attribute is deprecated in newer versions of PyTorch Lightning. Using `trainer.lightning_module` is the recommended approach for accessing the `LightningModule` instance, which encapsulates our model, training logic, and related components.
- This pull request updates our codebase to align with the latest best practices in PyTorch Lightning by replacing all instances of trainer.model with `trainer.lightning_module`.
Replaced all occurrences of trainer.model with trainer.lightning_module
For more information about code review checklists, see the [Code Review Checklist](https://github.com/openvinotoolkit/anomalib/blob/main/docs/source/markdown/guides/developer/code_review_checkli …
> Refactor Lightning's `trainer.model` to `trainer.lightning_module`

- pyproject.toml
Reverts openvinotoolkit/anomalib#2189
This version bump breaks the winclip onnx export
> Revert "Update open-clip-torch requirement from <2.26.1,>=2.23.0 to >=2.23.0,<2.26.2"

- src/anomalib/data/base/dataset.py
- src/anomalib/dataclasses/__init__.py
- src/anomalib/dataclasses/numpy.py
- src/anomalib/dataclasses/torch.py
- Rename Item to DatasetItem
- Some ruff fixes.
> Rename Item to DatasetItem

- pyproject.toml
- This PR updates the `setuptools` requirement in our `pyproject.toml` file to version 64.0.0 or higher. This change enables support for PEP 660, which allows for editable installs using the `build_editable` hook.
- Users were encountering error when attempting to install the project in editable mode:
- 🛠️ Fixes #2314 
> 🐞Update `setuptools` requirement for PEP 660 support

- src/anomalib/models/image/draem/lightning_model.py
- src/anomalib/models/image/dsr/lightning_model.py
- src/anomalib/models/image/rkde/lightning_model.py
- This PR adds `configure_transforms` method to dsr, draem and rkde. The method includes only resizing transformation. ImageNet normalization from default parent class method is skipped since these models don't use it.
- 🛠️ Fixes #1813
> Fix transforms for draem, dsr and rkde

- src/anomalib/models/components/base/anomaly_module.py
- This PR fixes a problem where AttributeError would occur if model, trained without normalization metrics, was loaded from checkpoint.
- 🛠️ Fixes #2253
> Add check before loading metrics data from checkpoint

- src/anomalib/engine/engine.py
- src/anomalib/models/image/vlm_ad/lightning_model.py
- src/anomalib/utils/visualization/__init__.py
- src/anomalib/utils/visualization/explanation.py
> Add explanation visualizer

- pyproject.toml
- src/anomalib/models/image/vlm_ad/backends/chat_gpt.py
- src/anomalib/models/image/vlm_ad/lightning_model.py
>  🔨 Allow setting API keys from env

- src/anomalib/__init__.py
- src/anomalib/callbacks/metrics.py
- src/anomalib/data/base/dataset.py
- src/anomalib/data/base/depth.py
- src/anomalib/deploy/inferencers/openvino_inferencer.py
- src/anomalib/engine/engine.py
- src/anomalib/models/image/vlm_ad/lightning_model.py
- tests/integration/model/test_models.py
>  🧪 Add tests

- .github/ISSUE_TEMPLATE/epic.yaml
> 🔨 Update the issue templates

- CHANGELOG.md
- configs/data/datumaro.yaml
- src/anomalib/data/__init__.py
- src/anomalib/data/image/__init__.py
- src/anomalib/data/image/datumaro.py
- tests/helpers/data.py
- tests/unit/data/image/test_datumaro.py
> 🚀 Add datumaro annotation dataloader

- src/anomalib/deploy/inferencers/openvino_inferencer.py
- This PR addresses an issue where importing the `OpenVINOInferencer` class would trigger a warning about OpenVINO not being installed, even when the class wasn't being used. The solution defers the OpenVINO import until the `OpenVINOInferencer` is actually instantiated.
- 🛠️ Fixes:
- #2384 
- #2140
- Removed global import of OpenVINO
- Moved OpenVINO import inside the `__init__` method of `OpenVINOInferencer`
- Added an `ImportError` raise if OpenVINO is not installed when the class is instantiated
For more information about code review checklists, see the [Code Review Checklist](https://github.com/openvinotoolkit/anomalib/blob/main/docs/source/markdown/guid …
> 🐞 Defer OpenVINO import to avoid unnecessary warnings

- CHANGELOG.md
- src/anomalib/__init__.py
- Release v1.2.0
- [Milestones](https://github.com/openvinotoolkit/anomalib/milestone/14)
> `v1.2.0` Release

- src/anomalib/cli/pipelines.py
- src/anomalib/cli/utils/openvino.py
- src/anomalib/deploy/inferencers/openvino_inferencer.py
- src/anomalib/loggers/wandb.py
- src/anomalib/models/components/base/export_mixin.py
- src/anomalib/models/image/vlm_ad/backends/chat_gpt.py
- src/anomalib/models/image/vlm_ad/backends/huggingface.py
- src/anomalib/models/image/vlm_ad/backends/ollama.py
- src/anomalib/utils/exceptions/imports.py
This PR replaces `package_available` with `module_available` from the `lightning-utilities` package.
- `package_available`: This function does not check that the actual import works; it simply checks whether the spec for that package exists. Passing this may actually cause an error on import depending on environment.
- `module_available`: This checks to see if the actual import will work. 
Due to the above differences, `anomalib install` is currently not running.
How I discovered this issue:
```shell
pip install -e .
anomalib install
To use other subcommand using `anomalib install`
Traceback (most recent call last):
File "/home/harimkan/workspace/repo/anomalib/venv/bin/anomalib", line 5, in <module>
from anomalib.cli.cli import main
File …
```
> 🐞Replace package_available with module_available

- src/anomalib/models/components/base/anomalib_module.py
- src/anomalib/models/image/winclip/lightning_model.py
- Quick PR to remove the `setup` and `_setup_` methods from the `AnomalibModule`. These methods are a leftover from v1, and no longer used in v2.
> remove setup methods from base module

- src/anomalib/models/components/base/anomalib_module.py
- tests/unit/models/components/base/test_anomaly_module.py
- Quick PR to reduce duplication in `AnomalibModule`. The 4 `_resolve_<component>` methods were very similar, so I replaced them with a common one. This improves readability of the base class.
> Simplify subcomponent resolve in base module

- src/anomalib/metrics/min_max.py
This fixed the (critical) bug in the min max scaler.
> fix minmax

- pyproject.toml
- src/anomalib/models/image/vlm_ad/backends/ollama.py
- 🛠️ Fixes https://github.com/openvinotoolkit/anomalib/issues/2453
> 🐞Fix ollama

- CHANGELOG.md
- README.md
- docs/source/markdown/guides/how_to/index.md
- docs/source/markdown/guides/how_to/training_on_intel_gpus/index.md
- src/anomalib/engine/__init__.py
- src/anomalib/engine/accelerator/__init__.py
- src/anomalib/engine/accelerator/xpu.py
- src/anomalib/engine/strategy/__init__.py
- src/anomalib/engine/strategy/xpu_single.py
- Add XPU accelerator
```bash
anomalib train --model Padim --data MVTec --trainer.accelerator xpu --trainer.strategy xpu_single
```
>  🚀 Add XPU accelerator

- src/anomalib/data/transforms/center_crop.py
- src/anomalib/deploy/inferencers/torch_inferencer.py
This PR fixes two problems that emerge when upgrading to PyTorch 2.6 and Torchvision 0.21.
- Fixes a problem with model loading in the torch inferencer, leading to CI failures. The problem was caused by a breaking change in PyTorch 2.6, where the default value of `weights_only` param of `torch.load` was changed from `False` to `True`. See https://pytorch.org/docs/main/notes/serialization.html#torch-load-with-weights-only-true for more information.
- Note that we may need to revisit how we load models in the torch inferencer, because loading with `weights_only==False` may lead to arbitrary code execution.
- Fixes a problem caused by the internal renaming of `Transform._transform` to `Transform.transform` in Torchvision 0.21.
Before you submit your …
> Fix latest torch and torchvision compatibility

- src/anomalib/post_processing/one_class.py
- tests/unit/post_processing/test_post_processor.py
Fixes visualization issue when dataset has no GT masks. In this case, we need to explicitly use the image threshold as a surrogate value for the pixel threshold. This was previously not accounted for by the post processor.
- Adds properties for retrieving image and pixel threshold to post-processor.
- Pixel threshold property returns image threshold value when pixel threshold is not available.
- Adds a basic set of unit tests for the OneClassPostProcessor. This may need to be extended in the future to cover full functionality and all edge cases.
For more information about code review checklists, see the [Code Review …
> Fix post-processing visualization issues

- src/anomalib/post_processing/one_class.py
- tests/unit/post_processing/test_post_processor.py
This PR adds configuration options to the `OneClassPostProcessor` class.
- Adds `enable_thresholding` and `enable_normalization` arguments and corresponding logic to `OneClassPostProcessor`.
- Adds `enable_threshold_matching` argument, which determines if the post-processor should use the image threshold for pixel-level predictions when the pixel-threshold is not available, and vice-versa.
- Minor simplification in sensitivity logic: Use 0.5 value as default instead of None
- Adds unit tests for `OneClassPostProcessor` class.
For more information about code review checklists, see the [Code Review Checklist](https://github.com/openvinotoolkit/anomalib/blob/mai …
> Add configuration options to PostProcessor

- src/anomalib/data/__init__.py
- src/anomalib/data/datamodules/__init__.py
- After renaming `MVTec` to `MVTecAD`, the relative import path to import MVTec is broken. This PR reverts that functionality back for compatibility.
```python
from anomalib.data import MVTec
from anomalib.data import MVTec # ❌ Broken
from anomalib.data import MVTecAD
from anomalib.data import MVTec    # ✅ Deprecated, but works
from anomalib.data import MVTecAD
```
> Add MVTec backward compatibility

- src/anomalib/models/__init__.py
- src/anomalib/models/video/fuvas/torch_model.py
- 🔒 Fix bandit and semgrep issues of Fuvas video anomaly detection model.
> 🔒 Fix bandit and semgrep issues of Fuvas video anomaly detection model.

- src/anomalib/models/image/supersimplenet/README.md
- src/anomalib/models/image/supersimplenet/lightning_model.py
- src/anomalib/models/image/supersimplenet/torch_model.py
- This PR adds a fix for SuperSimpleNet, where incorrect pretrained weights were used.
- 🛠️ Fixes #2688 
> Fix SuperSimpleNet pretrained weights.

- src/anomalib/callbacks/model_loader.py
- src/anomalib/deploy/inferencers/torch_inferencer.py
- src/anomalib/models/__init__.py
- src/anomalib/models/image/dsr/torch_model.py
- src/anomalib/models/image/efficient_ad/lightning_model.py
- src/anomalib/models/video/ai_vad/clip/clip.py
- src/anomalib/utils/path.py
- tests/integration/model/test_models.py
- tests/integration/tools/test_gradio_entrypoint.py
- tests/integration/tools/test_torch_entrypoint.py
- tests/unit/deploy/test_inferencer.py
**Issue:**
This PR addresses a critical security vulnerability related to the usage of `torch.load` within the `TorchInferencer`. The `torch.load` function, by default, uses Python's `pickle` module, which can lead to arbitrary code execution if a malicious model file (`.pt` or `.pth`) is loaded. An attacker could craft a model file that, when loaded, executes arbitrary code on the user's system.
This issue was identified by static code analyzers and is a known risk associated with unpickling data from untrusted sources. While PyTorch's `weights_only=True` parameter offers some mitigation, it doesn't fully protect against all potential attack vectors, such as path traversal for arbitrary file overwrite, as highlighted in recent research.
**Solution:**
To mitigate this risk, we have …
> 🔒 Security Fix: Mitigate Remote Code Execution Risk in `torch.load`

- CHANGELOG.md
- docs/source/markdown/guides/reference/data/datamodules/image.md
- docs/source/markdown/guides/reference/data/datamodules/image/tabular.md
- examples/configs/data/tabular.yaml
- examples/notebooks/100_datamodules/105_tabular.ipynb
- src/anomalib/data/__init__.py
- src/anomalib/data/datamodules/__init__.py
- src/anomalib/data/datamodules/image/__init__.py
- src/anomalib/data/datamodules/image/tabular.py
- src/anomalib/data/datasets/__init__.py
- src/anomalib/data/datasets/image/__init__.py
- src/anomalib/data/datasets/image/tabular.py
- tests/conftest.py
- tests/helpers/data.py
- tests/unit/data/datamodule/image/test_tabular.py
Hi, I submitted a similar PR about six months ago (PR #2403). It has not been reviewed yet, and in the meantime, Anomalib has gone from v1 to v2. Therefore, I decided to refactor the feature according to the new structure and submit it as a new PR.
* This PR adds the ``Tabular`` datamodule which is instantiated directly from a pandas ``DataFrame``. It is an alternative to the ``Folder`` datamodule for custom datasets where the labels are not encoded in the directory structure. Useful for situations where labels are refined regularly or for sub-sampling large datasets without copying or moving files.
* The datamodule also includes a ``from_file`` constructor which loads the data from a tabular file supported by pandas.
Before you submit your pull …
> Tabular datamodule (Custom dataset from DataFrame, CSV, or Parquet)

- src/anomalib/data/utils/image.py
- tests/unit/data/utils/test_image.py
- **Issue**: When loading gt masks with the `read_mask` function, only pixel values of 255 would be set as anomalous (value of 1) when loaded with `as_tensor=True`
- **Where did it cause problems**? The [MVTecLOCODataset](https://github.com/open-edge-platform/anomalib/blob/3fe113ff08a1add0e39406ceec583f4ec7a9cca8/src/anomalib/data/datasets/image/mvtec_loco.py#L64) has anomalous pixels with values below 255, since it assigns different values for different anomalies, leading to empty gt masks
- **Fix**: in [`read_mask(...)`](https://github.com/open-edge-platform/anomalib/blob/3fe113ff08a1add0e39406ceec583f4ec7a9cca8/src/anomalib/data/utils/image.py#L323) instead of dividing by 255 and then casting to torch.uint8 (which results in 0 values for any pixel values less than 255), pixels are set …
> 🐞fix(data): Fixed bug where MVTecLOCO GT Masks were not loaded correctly

- src/anomalib/cli/cli.py
- src/anomalib/utils/config.py
- Currently it is opaque to the users why the CLI fails. This minor change also shows the import error
```diff
anomalib train --model Padim
To use other subcommand using `anomalib install`
+Import failed: No module named 'FrEIA'. Please install the required dependencies.
Usage: anomalib [-h] [-c CONFIG] [--print_config [=flags]] {install} ...
error: argument subcommand: invalid choice: 'train' (choose from 'install')
```
> ♻️ refactor(cli): show import error in CLI

- docs/source/markdown/get_started/anomalib.md
- examples/api/01_getting_started/basic_openvino_inference.py
- examples/api/01_getting_started/basic_torch_inference.py
- examples/api/01_getting_started/basic_training.py
- examples/cli/01_getting_started/basic_training.sh
After reading #2892, I fixed the 'Anomalib in 15 Minutes' train and inference code to match 2.1.0 anomalib version.
- Changed `basic_training.py` to use **Patchcore** instead of EfficientAD, with examples of overriding config.
- Added test and export example in `basic_training.py`.
- Changed `basic_inference.py` to use Patchcore with `engine.predict()`.
- Added `basic_openvino_inference.py` to demonstrate image inference with `OpenVINOInferencer`.
- Added `basic_torch_inference.py` file with legacy warning.  
⚠️ Note: `TorchInferencer` is marked as legacy. Consider removing this example if maintainers prefer focusing only on `Engine.predict()`.
- Updated `basic_training.sh` to match the behavior of `basic_training.py`.
Before you submit your pull …
> 📚 fix(docs): fixed the "Anomalib in 15 Minutes" train and inference code

- src/anomalib/data/datamodules/image/vad.py
- src/anomalib/data/datasets/image/vad.py
- tests/helpers/data.py
Added ground truth masks to the VAD dataset (I am the author of [the original dataset](https://github.com/abc-125/vad)).
- Replaced link and hashsum in src/anomalib/data/datamodules/image/vad.py
- Added ground truth masks to src/anomalib/data/datasets/image/vad.py
- Updated tests in tests/helpers/data.py
> 🚀 feat(data): added ground truth masks to VAD dataset

- .github/actions/security/semgrep/action.yaml
- semgrep fails in certain actions as it checks uv.lock and complains about api being present.
> 🔨 fix(semgrep): ignore uv.lock in semgrep

- application/ui/src/router.tsx
By moving all of the routes into a single root route we can make sure that all routes are rendered inside of an layout that has a suspense and error boundary.
> chore(inspect): Improve error and suspense handling in router

- application/backend/src/db/engine.py
- application/backend/src/settings.py
This fixes an issue where the training worker wasn't able to get a lock on the sqlite database. As a result when it tried to get all pending jobs the query it would execute would stall indefinitely.
> 🐛 fix(inspect): Use null pool for async engine
