open-edge-platform/anomalib

.github/workflows/tox.yml
tox.ini

Limit number of parallel runs in Tests

Limit parallel runners

---

.github/workflows/docs.yml
.github/workflows/tox.yml
README.md

- Use temp folder to deal with folder issues in pipeline.

Fix docs pipeline 📄

---

anomalib/data/mvtec.py

- Shuffle the train dataloader in mvtec.

Shuffle train dataloader

---

anomalib/__init__.py
setup.py

- Bump up the version to 0.2.4

Bump up the version to 0.2.4

---

anomalib/data/__init__.py
anomalib/data/mvtec.py
tests/pre_merge/datasets/test_dataset.py

Refactor data and add @DATAMODULE_REGISTRY

---

anomalib/pre_processing/tiler.py
anomalib/utils/callbacks/__init__.py
anomalib/utils/callbacks/save_to_csv.py
anomalib/utils/callbacks/tiler.py
anomalib/utils/callbacks/visualizer_callback.py
tests/pre_merge/utils/callbacks/visualizer_callback/dummy_lightning_model.py
tests/pre_merge/utils/callbacks/visualizer_callback/test_visualizer.py
tests/utils/callbacks/__init__.py
tests/utils/callbacks/visualizer_callback/dummy_lightning_model.py
tests/utils/callbacks/visualizer_callback/test_visualizer.py

- This design modifies the callbacks to be compatible with the upcoming PL-CLI

Add/Update Callbacks

---

README.md
anomalib/models/ganomaly/torch_model.py
anomalib/utils/callbacks/nncf_callback.py
tests/nightly/models/test_model_nightly.py
third-party-programs.txt
tools/benchmarking/benchmark.py

Add third-party-programs.txt and update license

Add third-party-programs.txt file and update license

---

anomalib/models/cflow/backbone.py
anomalib/models/cflow/config.yaml
anomalib/models/cflow/model.py
anomalib/models/components/__init__.py
anomalib/models/components/base/__init__.py
anomalib/models/components/base/anomalib_module.py
anomalib/models/components/base/anomaly_module.py
anomalib/models/dfkde/model.py
anomalib/models/dfm/model.py
anomalib/models/ganomaly/model.py
anomalib/models/padim/__init__.py
anomalib/models/padim/model.py
anomalib/models/patchcore/model.py
anomalib/models/stfpm/model.py
tests/pre_merge/utils/callbacks/visualizer_callback/dummy_lightning_model.py
tox.ini

- This PR removes `hparams` from class constructor and uses explicit arguments, which will be automatically parsed by jsonargparse in pytorch lightning cli. 
- This is a prep PR for the upcoming CLI.

Refactor Models and Add PL-CLI Supported Models.

---

tools/train.py

- This PR makes sure that the best, not the latest model is used when evaluating after training.
- Fixes https://github.com/openvinotoolkit/anomalib/issues/63

load best model from checkpoint

---

.github/workflows/docs.yml

- Quick fix to ensure docs build runs only on isea-server as it is failing on the learner as it has not been configured yet.
🏃‍♂️ https://github.com/openvinotoolkit/anomalib/runs/6107591912?check_suite_focus=true

🔨 Minor fix: Ensure docs build runs only on isea-server

---

README.md
anomalib/config/config.py
anomalib/deploy/inferencers/openvino.py
docs/source/guides/getting_started.rst
tests/helpers/config.py
tests/pre_merge/utils/callbacks/normalization_callback/test_normalization_callback.py
tests/pre_merge/utils/callbacks/openvino_callback/test_openvino.py
tests/pre_merge/utils/metrics/test_adaptive_threshold.py
tools/benchmarking/README.md
tools/hpo/wandb_sweep.py
tools/inference.py
tools/test.py
tools/train.py

Reverts openvinotoolkit/anomalib#246

Revert "🏷  Rename `--model_config_path` to `config`"

---

README.md
anomalib/config/config.py
anomalib/deploy/inferencers/openvino.py
docs/source/guides/getting_started.rst
tests/helpers/config.py
tests/pre_merge/utils/callbacks/normalization_callback/test_normalization_callback.py
tests/pre_merge/utils/callbacks/openvino_callback/test_openvino.py
tests/pre_merge/utils/metrics/test_adaptive_threshold.py
tools/benchmarking/README.md
tools/hpo/wandb_sweep.py
tools/inference.py
tools/test.py
tools/train.py

- This is a leftover that should have been addressed in #246.

➕ Add `--model_config_path` deprecation warning to `inference.py`

---

anomalib/data/mvtec.py

- 🛠 Fix broken mvtec link, and split url to fit to 120.

🛠 Fix broken mvtec link, and split url to fit to 120

---

docs/source/guides/export.rst
docs/source/guides/inference.rst
docs/source/index.rst

- Adds documentation for export, optimization and inference. Should probably be merged after https://github.com/openvinotoolkit/anomalib/pull/298, since it describes the new pytorch inferencer format.
Closes #259

📜 Add Inference Documentation

---

.github/workflows/docs.yml

- Remove docs.txt requirement for docs build stage

Remove docs requirements

---

CHANGELOG.md
anomalib/__init__.py

- This is minor bug-fix pr to release v0.3.5

v0.3.5 - Minor bug-fix release

---

anomalib/utils/callbacks/__init__.py
anomalib/utils/cli/cli.py
configs/model/cflow.yaml
configs/model/dfkde.yaml
configs/model/dfm.yaml
configs/model/draem.yaml
configs/model/fastflow.yaml
configs/model/ganomaly.yaml
configs/model/padim.yaml
configs/model/patchcore.yaml
configs/model/reverse_distillation.yaml
configs/model/stfpm.yaml

- We mention that new cli will be used in version 0.3.4. It should be 0.4.0. I have updated the warning accordingly
- Fixes #454

🐞 Fix Visualization keys in new CLI

---

.github/labeler.yml
.github/workflows/labeler.yml

- Add github pr labeler to automatically label PRs

Add github pr labeler to automatically label PRs 

---

.github/labeler.yml
.github/workflows/pre_merge.yml

🐞 Change if check

---

README.md

Updated README to include example for exporting model to OpenVINO and ONNX. Removed reference to previous way of getting an OpenVINO model.

Updated documentation to add examples for exporting model

---

anomalib/utils/cli/cli.py
configs/model/fastflow.yaml

- This PR fixes category check when folder dataset is used with anomalib CLI.
- Fixes #484

🐞 Fix category check for folder dataset in anomalib CLI

---

anomalib/deploy/optimize.py

- Check the return code for error
- Fixes #569

🔨 Check for successful openvino conversion

---

CHANGELOG.md
anomalib/__init__.py

This is to release v0.3.7
- Bump up the version in `anomalib/__init__.py`
- Add the changes to `CHANGELOG.md`

Release v0.3.7

---

anomalib/data/utils/generators/perlin.py
anomalib/models/cflow/utils.py
anomalib/models/components/dimensionality_reduction/random_projection.py
anomalib/models/components/stats/kde.py
anomalib/models/fastflow/anomaly_map.py
anomalib/models/fastflow/loss.py
anomalib/models/ganomaly/torch_model.py
anomalib/models/patchcore/torch_model.py

- This is to address the black formatting issues.

Fix `black` formatting issues.

---

requirements/base.txt

- Fixes torchmetrics version to 0.10.3 as more development efforts are required for upgrading to 0.11.0. We can revisit this later on.
- Fixes #753

🚨 Fix torchmetrics version

---

.github/ISSUE_TEMPLATE/task.yaml

- Rename feature request template to task

Rename feature to task

---

anomalib/models/patchcore/torch_model.py

- Fixes #715 partially:
- fix image-level anomaly score for PatchCore with test_batch_size > 1
- Background: `embedding` was reshaped to `(Batch*Patch*Patch, Embedding)` but the indices in `max_patches` are unaware of the batch size, so in step 4, `embedding[max_patches]` returns patches of the first image for all images in the batch.
- also clearify some comments

Fix image-level anomaly score for PatchCore with test_batch_size > 1

---

CONTRIBUTING.md
docs/source/developer_guide/pre_commit_hooks.rst

- Update development instructions in CONTIBUTING.md. The instructions are simplified and now only include pre-commit (third party developers don't need to use tox).
- Update The pre-commit guide in the documentation.

Update development instructions

---

anomalib/models/dfkde/config.yaml

- Quick fix that removes an unused parameter from the DFKDE default config. (see https://github.com/openvinotoolkit/anomalib/discussions/669).

Remove unused DFKDE parameter

---

.github/workflows/pre_merge.yml
CHANGELOG.md

- Pre-empt running jobs
- Don't run on draft PR

⚙️ Modify pre_merge workflow

---

anomalib/deploy/inferencers/base_inferencer.py
anomalib/deploy/inferencers/openvino_inferencer.py
anomalib/deploy/inferencers/torch_inferencer.py
anomalib/models/components/base/anomaly_module.py
anomalib/post_processing/post_process.py
anomalib/post_processing/visualizer.py
anomalib/utils/callbacks/min_max_normalization.py

- Some improvements for the detection task type
- Add normalization and thresholding for detection (bbox) predictions.
- Rename `boxes_scores` key in outputs dict to `box_scores`
- Improve visualization. We can now visualize all regions of interest, including the ones that were not labeled anomalous after applying the threshold. This is useful for region-based models, as it allows us to check the quality of the region extractor predictions. For example:

Detection improvements

---

tests/nightly/__init__.py
tests/pre_merge/utils/__init__.py

- Add mising `__init__.py` files to `tests` folder.
- Due to these missing files, VS Code Test Explorer was not able to detect the tests.

Add missing init files in tests folder

---

anomalib/data/btech.py

Fix #871 BTech mask_image naming bug (*.bm.png)

---

CHANGELOG.md
anomalib/data/__init__.py
anomalib/data/avenue.py
anomalib/data/shanghaitech.py
anomalib/data/utils/video.py
tests/pre_merge/datasets/test_datamodule.py

- This PR adds adapters for the [ShanghaiTech Campus](https://svip-lab.github.io/dataset/campus_dataset.html) video anomaly detection dataset.
- ~~CI will fail, because the dataset is not yet installed on the CI machine.~~
- There is some code duplication between the `ShanghaiTechTestClipsIndexer` and the `UCSDpedClipsIndexer` classes. I will address this in a separate PR because it will require some refactor.

Add ShanghaiTech Campus dataset

---

notebooks/100_datamodules/101_btech.ipynb
notebooks/100_datamodules/102_mvtec.ipynb
notebooks/100_datamodules/103_folder.ipynb

- Improve ordering and descriptions of dataset notebooks.
- Fix bug causing notebooks to fail when dataset not installed on system.
- Fixes https://github.com/openvinotoolkit/anomalib/issues/873

Refactor datamodule and dataset notebooks

---

README.md

Update badge url for coverage to main branch

---

requirements/base.txt

- anomalib currently requires a fixed version. This PR loosen the `timm` version.

Loosen timm version

---

README.md
anomalib/__init__.py

- Change the version to dev
- Fix image paths in readme file.

Change the version to dev, and fix image paths in readme file.

---

.github/workflows/pre_merge.yml

Signed-off-by: Yunchu Lee <yunchu.lee@intel.com>

[CI] Added codecov token argument

---

requirements/base.txt

Loosen torchvision and torchtext version constraints

---

CHANGELOG.md
anomalib/__init__.py

- Bump version to `0.4.0rc2`
- Add the changes to `CHANGELOG.md`

Bump version to `0.4.0rc2`

---

requirements/base.txt
requirements/extras.txt

Fixes #905 
(should this go in `base.txt`, or `extras.txt`?)
Now that notebooks have optional ability to fetch get repo using `git.repo` `Repo` module, need to install dependency.
- Fixes #905

Add GitPython to requirements/base.txt

---

requirements/openvino.txt

- Bump OpenVINO version
- Fixes installing wrong numpy version causing snyk scans to raise alerts.
- Add export support to RKDE model.

Bump OpenVINO version

---

CHANGELOG.md
anomalib/__init__.py

Release v0.4.0

---

CHANGELOG.md

- Add a new section to changelog

Add unreleased section to CHANGELOG.md

---

src/anomalib/models/patchcore/README.md

Show images

---

docs/source/how_to_guides/train_custom_data.rst

- There were several troublesome issues in the train-custom-data [tutorial](https://openvinotoolkit.github.io/anomalib/how_to_guides/train_custom_data.html) 
- Updated the relevant .rst [file](https://github.com/Ravindu987/anomalib/blob/Fix-Tutorial/docs/source/how_to_guides/train_custom_data.rst) 
- Fixes #984

Fix issue in tutorial

---

src/anomalib/models/components/layers/sspcab.py

This fix follows the official implementation for the SSPCAB by the original author
- Fixes #839

[Bug: 839] Crop in SSPCAB implementation

---

CHANGELOG.md
src/anomalib/__init__.py

- Update main to dev
- Update changelog

Update main to dev

---

src/anomalib/pre_processing/tiler.py

fix example code.
change 
from anomalib.data.tiler import Tiler
to
from anomalib.pre_processing import Tiler

fix tile import typo

---

.github/workflows/upload_coverage.yml

for testing the workflow which will be triggered by `pre-merge` workflow completed event.

added a test workflow to stick to the pr-check workflow completed event

---

CHANGELOG.md
src/anomalib/models/cfa/lightning_model.py
src/anomalib/models/cfa/torch_model.py
src/anomalib/models/cflow/lightning_model.py
src/anomalib/models/cflow/torch_model.py
src/anomalib/models/csflow/lightning_model.py
src/anomalib/models/csflow/torch_model.py
src/anomalib/models/dfkde/lightning_model.py
src/anomalib/models/dfkde/torch_model.py
src/anomalib/models/dfm/lightning_model.py
src/anomalib/models/dfm/torch_model.py
src/anomalib/models/efficient_ad/lightning_model.py
src/anomalib/models/efficient_ad/torch_model.py
src/anomalib/models/fastflow/config.yaml
src/anomalib/models/fastflow/lightning_model.py
src/anomalib/models/fastflow/torch_model.py
src/anomalib/models/ganomaly/lightning_model.py
src/anomalib/models/ganomaly/torch_model.py
src/anomalib/models/padim/config.yaml
src/anomalib/models/padim/lightning_model.py
src/anomalib/models/padim/torch_model.py
src/anomalib/models/patchcore/lightning_model.py
src/anomalib/models/patchcore/torch_model.py
src/anomalib/models/reverse_distillation/lightning_model.py
src/anomalib/models/reverse_distillation/torch_model.py
src/anomalib/models/stfpm/config.yaml
src/anomalib/models/stfpm/lightning_model.py
src/anomalib/models/stfpm/torch_model.py

Reverts openvinotoolkit/anomalib#1169

Revert "Add default values to algorithms "

---

.github/CODEOWNERS
.readthedocs.yaml
pyproject.toml
requirements/loggers.txt
src/anomalib/utils/sweep/__init__.py
src/anomalib/utils/sweep/utils.py
tools/benchmarking/benchmark.py
tools/benchmarking/utils/__init__.py
tools/benchmarking/utils/metrics.py

Merge main to feature/benchmarking

---

src/anomalib/models/cfa/README.md
src/anomalib/models/cflow/README.md
src/anomalib/models/csflow/README.md
src/anomalib/models/draem/README.md
src/anomalib/models/fastflow/README.md
src/anomalib/models/ganomaly/README.md
src/anomalib/models/padim/README.md
src/anomalib/models/patchcore/README.md
src/anomalib/models/reverse_distillation/README.md
src/anomalib/models/stfpm/README.md

This PR fixes links to model architecture images in model readmes.

Fix links to model architecture images

---

CHANGELOG.md
src/anomalib/__init__.py

- This is to release v0.7.0 that adds the following changes
- AUPRO binning capability by @yann-cv in https://github.com/openvinotoolkit/anomalib/pull/1145
- Add support for receiving dataset paths as a list by @harimkang in https://github.com/openvinotoolkit/anomalib/pull/1265
- Add modelAPI compatible OpenVINO export by @ashwinvaidya17 in https://github.com/openvinotoolkit/anomalib/pull/1219
- Enable training with only normal images for MVTec by @djdameln in https://github.com/openvinotoolkit/anomalib/pull/1241
- Improve default settings of EfficientAD in https://github.com/openvinotoolkit/anomalib/pull/1143
- Added the tracer_kwargs to the TorchFXFeatureExtractor class by @JoaoGuibs in https://github.com/openvinotoolkit/anomalib/pull/1214
- Replace cdist in Patchcore by @blaz-r in …

Release `v0.7.0`

---

docs/source/tutorials/inference.rst

Fixing typo in docs
<details>
- [x ] Documentation update
</details>
<details>
</details>

fix(docs): typo

---

README.md

<details>
</details>
<details>
</details>

README: Synchronize OV version with requirements

---

requirements/base.txt

updates the timm version to 0.6.13, this includes a fix for python3.11 related dataclass problems.
<details>
</details>
<details>
</details>

chore(deps): update timm to 0.6.13

---

src/anomalib/models/ganomaly/lightning_model.py

Switch to manual optimization for Ganomaly in the new CLI design. This is needed because automatic optimization is deprecated for multiple optimizers. I checked the other models and Ganomaly seems to be the only one affected.
<details>
</details>
<details>
</details>

[Custom Trainer] Switch to manual optimization for ganomaly

---

.pre-commit-config.yaml
requirements/loggers.txt
src/anomalib/deploy/inferencers/torch_inferencer.py
tests/conftest.py
tests/integration/cli/test_cli.py
tests/unit/utils/callbacks/test_normalization_callback.py
tox.ini

- Add ruff check to tests.
<details>
</details>
<details>
</details>

Add ruff checks to tests

---

setup.py

I came across this (#1041) issue that went stale due to minor problems with formatting from what I can see. I decided to revive it since it was a rather easy way to try and contribute and help :) thank you for your time and this wonderful library.
- Fixes #1041
<details>
<summary>Formatted previous contribution that was stopped due to formatting issues</summary>
</details>
<details>
</details>

preexisting OpenCV version check added to `setup.py`, ran formatting pre-commit hooks on previous contribution.

---

src/anomalib/engine/engine.py
src/anomalib/utils/cli/cli.py

- Add train subcommand.
Note: I think once all the test stuff is settled, we need to revisit the cli.py file and refactor the code
<details>
</details>
<details>
</details>

[Custom Trainer] Add train subcommand

---

src/anomalib/engine/engine.py
tests/conftest.py
tests/integration/cli/test_cli.py

- Limits the CLI tests to only one model to tests e2e functionality.
- Removes unnecessary methods from `conftest`.
<details>
</details>
<details>
</details>

Refactor tests Part 1

---

src/anomalib/models/image/fastflow/README.md

This PR adds the average score of FastFlow's performance results to tables in the corresponding README.md file.
- Fixes #1586
<details>
</details>
<details>
</details>

[Docs] Add average score to the FastFlow's performance results tables

---

notebooks/000_getting_started/001_getting_started.ipynb
notebooks/300_benchmarking/301_benchmarking.ipynb
notebooks/400_openvino/401_nncf.ipynb
src/anomalib/callbacks/nncf/callback.py
src/anomalib/deploy/__init__.py
src/anomalib/deploy/export.py
src/anomalib/engine/engine.py
tests/integration/cli/test_cli.py
tests/unit/deploy/test_inferencer.py
tests/unit/pipelines/sweep/test_throughput.py

- Refactor `ExportMode` to `ExportType`

✏️ Refactor `ExportMode` to `ExportType`

---

requirements/loggers.txt
src/anomalib/deploy/export.py
src/anomalib/engine/engine.py
src/anomalib/pipelines/benchmarking/benchmark.py
tests/integration/tools/test_gradio_entrypoint.py
tests/integration/tools/test_openvino_entrypoint.py
tests/integration/tools/test_torch_entrypoint.py
tests/unit/deploy/test_inferencer.py
tests/unit/pipelines/sweep/test_throughput.py
tools/inference/gradio_inference.py

- Upgrade gradio version to 4.x
<details>
</details>
<details>
</details>

Upgrade gradio version to 4.x

---

notebooks/200_models/201_fastflow.ipynb
src/anomalib/cli/cli.py
src/anomalib/data/__init__.py
src/anomalib/data/predict.py
src/anomalib/engine/engine.py
tests/integration/model/test_models.py
tests/unit/data/test_inference.py
tests/unit/utils/test_visualizer.py
tools/inference/lightning_inference.py

- Rename InferenceDataset
<details>
</details>
<details>
</details>

✍ InferenceDataset->PredictDataset

---

src/anomalib/models/components/__init__.py
src/anomalib/models/components/feature_extractors/__init__.py
src/anomalib/models/components/feature_extractors/timm.py
src/anomalib/models/components/feature_extractors/utils.py
src/anomalib/models/image/cflow/torch_model.py
src/anomalib/models/image/dfkde/torch_model.py
src/anomalib/models/image/dfm/torch_model.py
src/anomalib/models/image/padim/torch_model.py
src/anomalib/models/image/patchcore/torch_model.py
src/anomalib/models/image/reverse_distillation/torch_model.py
src/anomalib/models/image/stfpm/loss.py
src/anomalib/models/image/stfpm/torch_model.py
tests/unit/models/test_feature_extractor.py

- Deprecates FeatureExtractor in 1.0 in favour of explicit TimmFeatureExtractor
<details>
</details>
<details>
</details>

`FeatureExtractor` -> `TimmFeatureExtractor`

---

.pre-commit-config.yaml
notebooks/000_getting_started/001_getting_started.ipynb
notebooks/100_datamodules/101_btech.ipynb
notebooks/100_datamodules/103_folder.ipynb
notebooks/200_models/201_fastflow.ipynb
src/anomalib/callbacks/nncf/callback.py
src/anomalib/data/utils/download.py
tox.ini

This PR is for fixing the medium severity issue reported by bandit scanning.
```
>> Issue: [B310:blacklist] Audit url open for permitted schemes. Allowing use of file:/ or custom schemes is often unexpected.
Severity: Medium   Confidence: High
CWE: CWE-22 (https://cwe.mitre.org/data/definitions/22.html)
More Info: https://bandit.readthedocs.io/en/1.7.6/blacklists/blacklist_calls.html#b310-urllib-urlopen
Location: /home/runner/work/anomalib/anomalib/src/anomalib/data/utils/download.py:298:12
297	        with DownloadProgressBar(unit="B", unit_scale=True, miniters=1, desc=info.name) as progress_bar:
298	            urlretrieve(  # noqa: S310
299	                url=f"{info.url}",
300	                filename=downloaded_file_path,
301	                reporthook=progress_bar.update_to,
302 …
```

Add URL verification for downloading dataset

---

src/anomalib/data/base/dataset.py
src/anomalib/utils/cv/connected_components.py

This PR addresses the training with the mps accelerator. Here are the changes:
- Convert mask to float32 after reading
- Convert the predicted mask to cpu before converting back to numpy.
🛠️ Fixes #1533 

🐞 v1 - Fix training with mps accelerator

---

src/anomalib/deploy/export.py
src/anomalib/engine/engine.py

<details>
</details>
<details>
</details>

Update Engine docstrings

---

src/anomalib/data/utils/image.py

This PR addresses the potential security issues that might stem from the input output filename generation.

🔒 v1 - Address security issues

---

.gitignore
src/anomalib/data/utils/image.py
tests/conftest.py
tests/unit/data/utils/test_image.py

This is to address path traversal issues that might potentially happen when `get_image_filenames` function.

🔒 Address path traversal issues

---

.github/pull_request_template.md
SECURITY.md

- This PR adds a `SECURITY.md` file to the root directory.
- 🛠️ Fixes CVS-129509

🔒 Add `SECURITY.md` file

---

src/anomalib/models/image/winclip/README.md

Give credit to the works that inspired our WinCLIP implementation in the README.
🛠️ Fixes # (issue number)

WinCLIP attribution

---

src/anomalib/models/image/rkde/lightning_model.py

Add URL to paper here also so that it also appears in readthedocs reference page at: https://anomalib.readthedocs.io/en/latest/markdown/guides/reference/models/image/rkde.html
- [SKIPPED - minor ] 📋 I have summarized my changes in the [CHANGELOG] - 
- [X ] 📚 I have made the necessary updates to the documentation (if applicable).
- [ N/A ] 🧪 I have written tests that support my changes and prove that my fix is effective or my feature works (if applicable).

📚 Update RKDE lighting model file header (hence docs) with paper URL

---

docs/source/markdown/guides/reference/data/depth/folder_3d.md
docs/source/markdown/guides/reference/data/depth/index.md
docs/source/markdown/guides/reference/data/depth/mvtec_3d.md
src/anomalib/data/depth/mvtec_3d.py

This PR is based on the closed PR https://github.com/openvinotoolkit/anomalib/pull/1636, which adds the sphinx-based docs for depth dataset, i.e., folder 3d and mvtec 3d.

📚 Add docs for the depth data

---

docs/source/markdown/guides/reference/models/image/index.md
src/anomalib/models/image/dsr/torch_model.py

Add missing docs for the DSR model

📚 Add docs for the DSR model

---

CHANGELOG.md
src/anomalib/__init__.py

- This is to update the CHANGELOG.md file before the release.

📚 Update the `CHANGELOG.md` file

---

src/anomalib/models/image/dfm/lightning_model.py
src/anomalib/models/image/fastflow/lightning_model.py

Add paper links for consistency, as the other models have also provided links to their papers.

📚 Add the missing paper link for the DFM and FastFlow models

---

src/anomalib/callbacks/normalization/utils.py
src/anomalib/callbacks/thresholding.py
src/anomalib/engine/engine.py
src/anomalib/utils/types/__init__.py

- Restore https://github.com/openvinotoolkit/anomalib/pull/1623/files

🔨 Refactor type alias

---

src/anomalib/cli/cli.py

- Remove these from the CLI.
- HPO and Benchmarking will be restored in 1.1 with the new pipeline redesign
- Restores https://github.com/openvinotoolkit/anomalib/pull/1545

🗑️Remove HPO and Benchmarking from CLI

---

src/anomalib/models/components/base/anomaly_module.py

- Very tiny fix but affects downstream tasks.

🚨Fix predict_step in AnomalyModule

---

README.md

- fix a typo in README: Change "API" to "CLI"

📚 Documentation update: fix a typo of README

---

CHANGELOG.md
src/anomalib/models/components/__init__.py
src/anomalib/models/components/base/__init__.py
src/anomalib/models/components/base/dynamic_buffer.py
src/anomalib/models/components/cluster/gmm.py
src/anomalib/models/components/dimensionality_reduction/pca.py
src/anomalib/models/components/stats/kde.py
src/anomalib/models/image/cfa/torch_model.py
src/anomalib/models/image/dfm/torch_model.py
src/anomalib/models/image/patchcore/torch_model.py
src/anomalib/models/image/winclip/torch_model.py
src/anomalib/models/video/ai_vad/density.py
tests/unit/models/components/base/test_dynamic_buffer_mixin.py

- Addresses https://github.com/openvinotoolkit/anomalib/issues/1649

🔨 Rename DynamicBufferModule to DynamicBufferMixin

---

.readthedocs.yaml

Add explicit requirements to docs build workflow

---

CHANGELOG.md
src/anomalib/__init__.py

Version bump

---

notebooks/000_getting_started/001_getting_started.ipynb

- Update the getting started notebook documentation.

📚 Update the getting started notebook

---

.github/workflows/pre_merge.yml

🚧 Temporarily enable tests on hotfix branches

---

CHANGELOG.md

🛠️ Update changelog

---

src/anomalib/deploy/inferencers/openvino_inferencer.py

🔨  Update OpenVINO predict to handle normalization inside the method.

---

src/anomalib/callbacks/metrics.py
src/anomalib/metrics/__init__.py

Fix bug caused by incorrect checking of metric names.

Fix metric bug

---

src/anomalib/deploy/inferencers/torch_inferencer.py

Use LabelName ENUM for label assignment as in #1872 

Use LabelName ENUM for label assignment

---

.github/pull_request_template.md
.github/workflows/nightly.yml
.github/workflows/pre_merge.yml
CONTRIBUTING.md
README.md
docs/source/markdown/announcements/recognition.md
docs/source/markdown/get_started/anomalib.md
notebooks/100_datamodules/README.md
notebooks/500_use_cases/501_dobot/README.md
notebooks/README.md
pyproject.toml
requirements/openvino.txt
src/anomalib/deploy/inferencers/openvino_inferencer.py
src/anomalib/deploy/inferencers/torch_inferencer.py
src/anomalib/models/image/cfa/README.md
src/anomalib/models/image/cflow/README.md
src/anomalib/models/image/csflow/README.md
src/anomalib/models/image/draem/README.md
src/anomalib/models/image/dsr/README.md
src/anomalib/models/image/fastflow/README.md
src/anomalib/models/image/ganomaly/README.md
src/anomalib/models/image/padim/README.md
src/anomalib/models/image/patchcore/README.md
src/anomalib/models/image/reverse_distillation/README.md
src/anomalib/models/image/stfpm/README.md
src/anomalib/models/image/uflow/README.md
src/anomalib/models/image/winclip/README.md

- Bump onnx version as the previous version caused security issues

🔒 Bump onnx version as the previous version caused security issues

---

src/anomalib/data/utils/image.py

🐞 Add greyscale conversion

---

.github/workflows/publish.yml

- Based on my understanding of the issue, it looks like gpg import fails as it requests tty input. This PR disables tty import and sets `yes` to all prompts.

🐞 Fix publish workflow

---

.github/workflows/publish.yml

- use no-tty for signing the release

🐞 Disable tty prompt for gpg signing

---

src/anomalib/__init__.py

- Bump anomalib version from 1.0.1 to 1.1.0dev

Bump anomalib version from 1.0.1 to 1.1.0dev

---

.github/labeler.yml

Update github pr labeler

---

src/anomalib/deploy/inferencers/torch_inferencer.py

DFM returns score as the first item, the second one is an anomaly map.

Fix DFM PyTorch inference

---

CHANGELOG.md
src/anomalib/metrics/optimal_f1.py
tests/unit/metrics/test_optimal_f1.py

- Update OptimalF1 score
- Add tests

🛠️ Update OptimalF1 Score

---

src/anomalib/metrics/optimal_f1.py
tests/unit/metrics/test_optimal_f1.py

🚨Hotfix: compute precision recall on raw scores

---

README.md

💬 Add Discord badge to `README.md`

---

CHANGELOG.md
docs/source/markdown/guides/reference/models/image/index.md
docs/source/markdown/guides/reference/pipelines/base/generator.md
docs/source/markdown/guides/reference/pipelines/base/job.md
docs/source/markdown/guides/reference/pipelines/base/pipeline.md
docs/source/markdown/guides/reference/pipelines/benchmark/generator.md
docs/source/markdown/guides/reference/pipelines/benchmark/index.md
docs/source/markdown/guides/reference/pipelines/benchmark/job.md
docs/source/markdown/guides/reference/pipelines/index.md
docs/source/markdown/guides/reference/pipelines/runners/index.md
docs/source/markdown/guides/reference/pipelines/runners/parallel.md
docs/source/markdown/guides/reference/pipelines/runners/serial.md
docs/source/snippets/pipelines/benchmark/cli_anomalib.txt
docs/source/snippets/pipelines/benchmark/cli_tools.txt
src/anomalib/__init__.py
src/anomalib/pipelines/components/base/runner.py

Create changelog
- Merge release v1.1.0 into main

Release v1.1.0 

---

.github/workflows/publish.yml

Update the publish workflow

---

src/anomalib/__init__.py

- Bump Anomalib version to 1.2.0dev

Bump Anomalib version to 1.2.0dev

---

.github/workflows/code_scan.yml
.github/workflows/pre_merge.yml
.github/workflows/publish.yml
.github/workflows/upload_coverage.yml

- Set permissions for github workflows to address OpenSSF issues.

Set permissions for github workflows

---

CHANGELOG.md
configs/data/btech.yaml

- The root directory in btech.yaml has a spell error.

Fix uncorrect download path of btech dataset

---

src/anomalib/data/depth/folder_3d.py

Simplify folder 3d dataset

---

CHANGELOG.md
src/anomalib/__init__.py

Update changelog
- v1.1.1 Release

Release v1.1.1

---

src/anomalib/models/image/uflow/anomaly_map.py
src/anomalib/models/image/uflow/nfa_tree.py

- This PR fixes the pre-commit issues from PR #2104

Fix the pre-commit issues of UFlow

---

pyproject.toml
src/anomalib/models/__init__.py
src/anomalib/models/image/__init__.py
src/anomalib/models/image/vlm_ad/backends/huggingface.py

- Add missing `lightning-utilities` to the core dependencies
- Update the coverage ignore configuration 
- Remove `VlmAd`'s relative import from models to avoid missing optional dependencies.

🐞 Fix installation package issues

---

CHANGELOG.md
src/anomalib/__init__.py

- Update the `CHANGELOG.md`
- Update the version in `__init__`

Prepare v1.2.0 release

---

src/anomalib/__init__.py

Bump Anomalib version to `2.0.0dev` in `main`

---

CHANGELOG.md

- Update `CHANGELOG.md` file for v2.0.0 release

📚Update `CHANGELOG.md` file for v2.0.0 release

---

src/anomalib/__init__.py
src/anomalib/utils/visualization/base.py

- Version bump to `v2.0.0-beta.1`

Version bump to `v2.0.0-beta.1`

---

.github/workflows/_reusable-release-status.yaml
.github/workflows/release.yaml
README.md
src/anomalib/__init__.py

- This PR triggers the release process for beta releases. The current version only supports the production ready and rc versions 
- 

Add beta release support

---

examples/notebooks/700_metrics/701e_aupimo_advanced_iv.ipynb

🛠️ Fix pre-commit issues

---

.github/workflows/pr.yaml
.github/workflows/pre_merge.yml

Remove trigger on merge to main

---

.github/actions/pytest/action.yaml
examples/notebooks/700_metrics/701e_aupimo_advanced_iv.ipynb
pyproject.toml

- Bump deprecated v3 of the artifact actions

Bump deprecated v3 of the artifact actions

---

tests/unit/metrics/test_min_max.py

Adds some simple unit tests to test the basic functionality of the MinMax metric.

Add unit tests for MinMax metric

---

src/anomalib/models/components/base/export_mixin.py

Fixes #2524 
if this requires a comment in the changelog, let me know, or if i am just tripping and the name makes sense, please let me also know
- [ X] 🐞 Bug fix (non-breaking change which fixes an issue)
- [ X] 📋 I have summarized my changes in the [CHANGELOG](https://github.com/openvinotoolkit/anomalib/blob/main/CHANGELOG.md) and followed the guidelines for my type of change (skip for minor changes, documentation updates, and test enhancements).
- [ X] 📚 I have made the necessary updates to the documentation (if applicable).
- [X ] 🧪 I have written tests that support my changes and prove that my fix is effective or my feature works (if applicable).
For …

Fix onnx input parameter name

---

.github/workflows/dco_merge_group.yml

- We need this workflow because due to current limitation by DCO it does not run on merge groups

Add DCO merge group workflow configuration

---

CHANGELOG.md
src/anomalib/models/image/csflow/lightning_model.py
src/anomalib/models/image/fastflow/lightning_model.py
src/anomalib/models/image/ganomaly/lightning_model.py
src/anomalib/models/image/reverse_distillation/lightning_model.py
src/anomalib/models/image/uflow/lightning_model.py

- Hotfix for deployed instances of v1.1.
- Checks if model already exists before instantiation. This prevents an issue when the model is loaded using `load_from_checkpoint` method.

[Hotfix] check model attribute in setup method

---

CHANGELOG.md
src/anomalib/models/image/csflow/lightning_model.py
src/anomalib/models/image/fastflow/lightning_model.py
src/anomalib/models/image/ganomaly/lightning_model.py
src/anomalib/models/image/reverse_distillation/lightning_model.py
src/anomalib/models/image/uflow/lightning_model.py

Same as https://github.com/openvinotoolkit/anomalib/pull/2574, but for 1.1.3

[Hotfix] Model setup hotfix

---

src/anomalib/deploy/inferencers/openvino_inferencer.py
src/anomalib/models/image/winclip/lightning_model.py

- Fixes WinCLIP OpenVINO export
```python
"""Export winclip to OpenVINO and check the outputs."""
from pathlib import Path
import cv2
import numpy as np
from einops import rearrange
from PIL import Image
from rich.progress import track
from anomalib.data import MVTec, NumpyImageBatch
from anomalib.deploy import OpenVINOInferencer
from anomalib.engine import Engine
from anomalib.models.image import WinClip
def main():
model = WinClip()
datamodule = MVTec()
engine = Engine()
engine.test(model, datamodule=datamodule)
engine.export(model, export_type="openvino")
results_dir = Path("results/openvino")
results_dir.mkdir(parents=True, exist_ok=True)
inferencer = OpenVINOInferencer(path="results/WinClip/MVTec/bottle/latest/weights/openvino/model.xml")
image_paths = …
```

Keep weights in state dict when exporting

---

src/anomalib/models/components/stats/multi_variate_gaussian.py

This PR refactors the `MultiVariateGaussian` class to improve the stability and efficiency of the covariance matrix inversion process.  The reason for this change is that `torch.linalg.inv` does not work if the device `mps`. It returns `nan` instead. 
The changes include:
Regularization of the Covariance Matrix: A small regularization term is added to the diagonal of the covariance matrix to enhance numerical stability during inversion.
Device Handling: The code now checks if the device is `mps` and appropriately moves the covariance matrix to the CPU for inversion, ensuring that the inverse covariance matrix is stored on the correct device.
For more information about code review checklists, see …

Refactor MultiVariateGaussian for Improved Covariance Matrix Stability and Device Handling

---

CHANGELOG.md
README.md
src/anomalib/__init__.py

- This PR is to release Anomalib v2 stable version.

🚀 Anomalib v2 Stable Release

---

.github/workflows/_reusable-release-validation.yaml

- Increase timeout for release validation

Increase timeout for release validation

---

src/anomalib/__init__.py

- Bump the version to `2.1.0.dev`

Bump version to `2.1.0.dev`

---

CHANGELOG.md
src/anomalib/models/video/fuvas/README.md
src/anomalib/models/video/fuvas/lightning_model.py
src/anomalib/models/video/fuvas/torch_model.py
tests/integration/model/test_models.py

🚀 Add FUVAS Video Anomaly Detection Model

---

.github/actions/security/bandit/action.yaml
.github/actions/security/semgrep/action.yaml
.github/workflows/_reusable-security-scan.yaml
.github/workflows/pr.yaml
.github/workflows/security-checks.yaml
pyproject.toml

This PR refactors Semgrep and Bandit configurations and logic implemented in workflow, major improvements:
- In most cases `inputs.scan-scope  == "changed"` is used for checks on PR, therefore action outputs results into workflow log to simplify analysis; if `inputs.scan-scope  == "all"` - reports are generated in SARIF format and uploaded into Security tab.
- Semgrep does not support minimal severity, therefore all required security level shall be passed explicitly, logic updated.
- added several Semgrep rulesets, including [Trail of Bits](https://github.com/trailofbits/semgrep-rules) rule set targeted to AI/ML security issues
- `returntocorp/semgrep` container is used instead of Python package installation (minor speed improvements)
- now bandit and semgrep really fail on PR if any …

Semgrep and Bandit config refactor

---

src/anomalib/models/video/fuvas/lightning_model.py
src/anomalib/models/video/fuvas/torch_model.py

- Remove `TaskType` from `FUVAS` Video Anomaly Detection Model

🗑️ Remove `TaskType` from `FUVAS` Video Anomaly Detection Model

---

.github/ISSUE_TEMPLATE/feature_request.yaml

- This PR adds feature request template for users.

📚 Add feature request template

---

README.md

- Updated the incorrect Git clone URL in the “Install from Source” section of README.md.
- The previous URL pointed to https://github.com/openvinotoolkit/anomalib.git, which is outdated.
- This fix updates it to the current repository: https://github.com/open-edge-platform/anomalib.git.
- 🛠️ Fixes: N/A (no issue number associated)

docs: update installation guide with correct repository URL

---

CHANGELOG.md

Updates the CHANGELOG.md to include the PR : Enable tiled ensembe in v2 #2660

Add log for Tiled Ensemble PR

---

src/anomalib/engine/engine.py

- Small change that returns the metric from the test stage of the train method.

Return metrics from train

---

CHANGELOG.md
src/anomalib/data/__init__.py

Semgrep flags dynamic imports with arbitrary strings to be security risk. In this PR, such an import is replaced with a fixed import 

🔨 Fix Arbitrary imports in get_datamodule()

---

.github/actions/pytest/action.yaml
.github/actions/security/bandit/action.yaml
.github/actions/security/semgrep/action.yaml
.github/actions/security/trivy/action.yaml
.github/actions/security/zizmor/action.yaml
.github/workflows/_reusable-artifact-builder.yaml
.github/workflows/_reusable-code-quality.yaml
.github/workflows/_reusable-production-release-process.yaml
.github/workflows/_reusable-rc-release-process.yaml
.github/workflows/_reusable-release-publisher.yaml
.github/workflows/_reusable-release-status.yaml
.github/workflows/_reusable-release-validation.yaml
.github/workflows/_reusable-security-scan.yaml
.github/workflows/_reusable-test-suite.yaml
.github/workflows/_reusable-version-check.yaml
.github/workflows/pr.yaml
.github/workflows/pre_merge.yml
.github/workflows/release.yaml
.github/workflows/security-checks.yaml
.pre-commit-config.yaml

PR with minor changes to address Zizmor and CodeQL findings.
Was tested in fork.

Addressing Zizmor and CodeQL findings

---

.github/ISSUE_TEMPLATE/bug_report.yaml
.github/ISSUE_TEMPLATE/feature_request.yaml
.github/workflows/issue-management.yaml

- Add issue-management workflow to check for stale issues. We can populate more features later on.
- Polish bug report and feature request templates

Add `issue-management` workflow

---

.github/actions/security/bandit/README.md
.github/actions/security/semgrep/README.md
.github/actions/security/trivy/README.md
.github/actions/security/trivy/action.yaml
.github/workflows/_reusable-security-scan.yaml
pyproject.toml
src/anomalib/deploy/inferencers/torch_inferencer.py
src/anomalib/models/components/base/export_mixin.py
src/anomalib/models/video/ai_vad/clip/clip.py

- `B614` Bandit check was enabled, added comments to suppress Bandit and Semgrep false positives 
- in `src/anomalib/models/video/ai_vad/clip/clip.py` `weights_only` is set explicitly set to `True`, it shall not break functionality as `True` is a value by default
- Trivy composite action minor refactor, added Readme files to security composite actions 

Security composite actions minor changes

---

docs/source/markdown/guides/reference/data/datamodules/image.md
docs/source/markdown/guides/reference/data/datamodules/image/btech.md
docs/source/markdown/guides/reference/data/datamodules/image/datumaro.md
docs/source/markdown/guides/reference/data/datamodules/image/folder.md
docs/source/markdown/guides/reference/data/datamodules/image/kolektor.md
docs/source/markdown/guides/reference/data/datamodules/image/mvtecad.md
docs/source/markdown/guides/reference/data/datamodules/image/mvtecad2.md
docs/source/markdown/guides/reference/data/datamodules/image/mvtecloco.md
docs/source/markdown/guides/reference/data/datamodules/image/realiad.md
docs/source/markdown/guides/reference/data/datamodules/image/tabular.md
docs/source/markdown/guides/reference/data/datamodules/image/vad.md
docs/source/markdown/guides/reference/data/datamodules/image/visa.md
docs/source/markdown/guides/reference/data/datamodules/index.md

- Add missing datasets and datamodules
- Add cross-links between datasets and datamodules

📚 Update Data Docs

---

src/anomalib/models/image/efficient_ad/torch_model.py

- Updated example usage of EfficientAdModel to include model evaluation.
- Changed output format for anomaly map to reflect new structure.
- Adjusted output shapes in SmallPatchDescriptionNetwork and MediumPatchDescriptionNetwork.
- Set default value for teacher_out_channels in EfficientAdModel constructor.
- Updated copyright year to 2025.
🛠️ Fixes https://github.com/open-edge-platform/anomalib/issues/2690

📚 Docs: Refactor EfficientAdModel example and update output shapes

---

src/anomalib/data/dataclasses/torch/base.py

- This update modifies the ToNumpyMixin class to utilize the fields function from the dataclasses module, allowing for a more robust conversion of attributes to numpy arrays. The conversion now handles both torch tensors and objects with a to_numpy method, ensuring better compatibility and performance.
- 🛠️ Fixes #2645

fix(data): enhance `ToNumpyMixin` for improved tensor conversion

---

src/anomalib/visualization/image/item_visualizer.py

- This PR removes unnecessary warning log in `visualize_image_item` function to streamline visualization process.

refactor(visualizer): remove unnecessary warning log in `visualize_image_item`

---

pyproject.toml
src/anomalib/visualization/image/functional.py

- This PR updates the `pyproject.toml` to include Pillow version 10.1.0 as a dependency, which is necessary for supporting the size parameter in font loading. Additionally, the image font loading logic in `functional.py` has been modified to utilize the size parameter when loading the default font, enhancing text rendering capabilities in images.
- 🛠️ Fixes #2612

fix(visualization): modify the image font loading logic

---

.github/ISSUE_TEMPLATE/bug_report.yaml
.github/ISSUE_TEMPLATE/documentation.yaml
.github/ISSUE_TEMPLATE/epic.yaml
.github/ISSUE_TEMPLATE/question.yaml
.github/ISSUE_TEMPLATE/task.yaml
.github/ISSUE_TEMPLATE/user_story.yaml
.github/workflows/issue-management.yaml

This PR introduces a comprehensive update to the project's issue management system, aligning it with best practices to improve the contribution experience. Key changes include:
- Added new issue templates for documentation and questions, enhancing clarity and usability.
- Refined existing templates for consistency and improved communication.
- Enhanced the  workflow to automate triaging and stale issue management, ensuring the issue tracker remains organized.
These updates aim to streamline issue handling and foster better collaboration within the project.
For more information about code review checklists, see the [Code Review …

🔧 chore(ci): overhaul issue management process with new templates and enhanced workflow

---

examples/configs/data/mpdd.yaml
src/anomalib/data/__init__.py
src/anomalib/data/datamodules/__init__.py
src/anomalib/data/datamodules/image/__init__.py
src/anomalib/data/datamodules/image/mpdd.py
src/anomalib/data/datasets/__init__.py
src/anomalib/data/datasets/image/__init__.py
src/anomalib/data/datasets/image/mpdd.py
tests/helpers/data.py
tests/unit/data/datamodule/image/test_mpdd.py

- Add [MPDD](https://github.com/stepanje/MPDD) dataset

🚀 feat(data): add MPDD dataset

---

src/anomalib/data/datamodules/image/mvtecad2.py

`AnomalibCLI` uses jsonargparse to serialise `__init__` args.
For MVTecAD2, this turns:
```python
test_type: str | TestType = TestType.PUBLIC,
```
to "PUBLIC". Which causes this error:
```bash
ValueError: Does not validate against any of the Union subtypes
Subtypes: [<class 'NoneType'>, <class 'anomalib.data.datamodules.base.image.AnomalibDataModule'>]
Errors:
- Expected a <class 'NoneType'>
- 'PUBLIC' is not a valid TestType
Given value type: <class 'jsonargparse._namespace.Namespace'>
Given value: Namespace(class_path='anomalib.data.MVTecAD2', init_args=Namespace(root='./datasets/MVTec_AD_2', category='vial', train_batch_size=32, eval_batch_size=32, num_workers=8, 
train_augmentations=None, val_augmentations=None, test_augmentations=None, augmentations=None, test_type='PUBLIC', …
```

fix(data): MVTecAD2 CLI bug fix enum serialisation

---

src/anomalib/data/datasets/base/video.py
src/anomalib/metrics/pro.py
src/anomalib/models/components/cluster/gmm.py
src/anomalib/models/components/dimensionality_reduction/pca.py
src/anomalib/models/components/stats/kde.py
src/anomalib/models/image/cflow/torch_model.py
src/anomalib/models/image/dfm/torch_model.py
src/anomalib/models/image/patchcore/torch_model.py
src/anomalib/models/image/uflow/anomaly_map.py
src/anomalib/models/image/uflow/feature_extraction.py
src/anomalib/models/image/vlm_ad/backends/huggingface.py
src/anomalib/models/video/ai_vad/density.py
src/anomalib/models/video/ai_vad/regions.py
tests/unit/metrics/pimo/test_binary_classification_curve.py
tests/unit/metrics/test_adaptive_threshold.py
tests/unit/metrics/test_binning.py
tests/unit/metrics/test_pro.py
tests/unit/utils/callbacks/visualizer_callback/dummy_lightning_model.py

- Fix semgrep and bandit issues

🔧 chore: fix semgrep and bandit issues

---

examples/api/03_models/efficient_ad.py
src/anomalib/models/image/efficient_ad/lightning_model.py

This fixes the `NotImplementedError: ('{} cannot be pickled', '_SingleProcessDataLoaderIter')` if a custom pre processor is added to EfficientAD. 
The issue is, that the iterator instance used to generate the ImageNet samples cannot be pickled. The only feasable way to Prevent this seems to remove it from the python object state dict. Now, everytime the model is getting pickled, the imagenet Iterator is removed from a copy of the state dict.
It seems like a weird fix, but I tried everything else.
Excluding the object from `save_hyperparameters()`, storing the object in a dict, and so on
As long as the iterator remains in the object dictionary, torch will try to pickle it
Maybe someone knows a better fix for this?
- 🛠️ Fixes https://github.com/open-edge-platform/anomalib/issues/2831
- 🛠️ …

🐞 fix(model): EfficientAD `NotImplementedError: ('{} cannot be pickled', '_SingleProcessDataLoaderIter')`

---

src/anomalib/models/image/dfkde/torch_model.py
src/anomalib/models/image/dfm/torch_model.py
src/anomalib/models/image/padim/torch_model.py
src/anomalib/models/image/patchcore/torch_model.py

In PR #2813, we reduce the memory allocation but increase the reserved memory. This is caused by doing torch.cat repeatedly doesn't free memory (works fine in toy examples where you only do it once). PyTorch keeps old memory blocks to optimize performance, which can lead to high memory usage over time.
Patchcore:
Padim: 
Patchcore:
Padim:
I also changed dfm and dfkde to keep same memory bank code style.
#2886 
For more information about code review checklists, see the [Code Review Checklist](https://github.com/open-edge-platform/anomalib/blob/main/docs/ …

🐛 fix(model): Reduce memory reserved for memory bank based models PatchCore, Padim, Dfkde

---

.github/workflows/codeql.yml

This PR adds advanced CodeQL analysis workflow for security scanning

🚀 feat(workflow): add CodeQL analysis workflow for security scanning

---

app/ui/package-lock.json

chore: Update package lock

---

app/backend/.gitignore
app/backend/src/main.py

This PR updates list of allowed origins so sever can receive requests from the UI and adds db to git ignore file.

🔧 chore(inspect): Update allowed origins so server can receive requests from the UI

---

application/ui/src/features/inspect/projects-management/project-list-item/project-list-item.component.tsx
application/ui/src/features/inspect/projects-management/projects-list-panel.component.tsx

Updates the photo placeholder component because of https://github.com/open-edge-platform/geti/pull/1355.

refactor(inspect): Update photo placeholder to use indicator instead of email

---

application/ui/src/features/inspect/dataset/dataset-list.component.tsx
application/ui/src/features/inspect/dataset/dataset-status-panel.component.tsx

Addressed comments from https://github.com/open-edge-platform/anomalib/pull/2984.

🔄 refactor(inspect): Improvements to the jobs management and training

---

application/ui/src/features/inspect/dataset/dataset-status-panel.component.tsx

This PR adds more models that can be used for training and one minor followup to https://github.com/open-edge-platform/anomalib/pull/2992.

🔧 chore(inspect): Add more models to be used for training

---

application/backend/uv.lock

When I was trying to run server locally (`./run.sh`) I got the following error:
```
error: Failed to parse `uv.lock`
Caused by: TOML parse error at line 1, column 9
|
1 | version https://git-lfs.github.com/spec/v1
|         ^
expected `.`, `=`
```
Removing the `uv.lock` file and running `./run.sh` fixed the issue.

🔧 chore(inspect): Update uv.lock

---

CHANGELOG.md

  🔧  docs(changelog): Fix entries
